# -*- coding: utf-8 -*-
import os, sys
import base64
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

def install_font():
    b64fontfile = """AAEAAAASAQAABAAgRFNJRwAAAAEAAOyYAAAACEdERUYU+hVAAAABLAAAAHRHUE9TET15+AAAAaAA
    ACQeR1NVQtFei/UAACXAAAAM5k9TLzKJq5HmAAAyqAAAAGBjbWFwjkNOMwAAMwgAAAeEY3Z0IBU5
    IVMAAN3kAAAAjmZwZ21BHo58AADedAAADW1nYXNwAAAAEAAA3dwAAAAIZ2x5Zu8MIPwAADqMAACD
    DGhlYWQOtALZAAC9mAAAADZoaGVhBeADSgAAvdAAAAAkaG10eNalMzgAAL30AAAH6GxvY2HO2O8s
    AADF3AAAA/htYXhwA0EOVgAAydQAAAAgbmFtZeoppqAAAMn0AAAG53Bvc3QgkMQfAADQ3AAADQBw
    cmVwZfMzNAAA6+QAAACxAAEAAAAMAAAAAABeAAIADQAEAFkAAQBbAFwAAQBfAGkAAQBrAOUAAQDn
    AOgAAQDrAPUAAQD3ARcAAQGfAZ8AAQG5AbkAAQHQAdAAAQHSAdIAAQHTAeYAAwH3AfcAAQACAAMB
    0wHXAAIB2QHfAAIB4AHhAAEAAQAAAAoA2gKqAAJERkxUAA5sYXRuAB4ABAAAAAD//wADAAAACwAW
    ADoACUFaRSAARkNBVCAAUkNSVCAAXktBWiAAak1PTCAAdk5MRCAAglJPTSAAjlRBVCAAmlRSSyAA
    pgAA//8AAwABAAwAFwAA//8AAwACAA0AGAAA//8AAwADAA4AGQAA//8AAwAEAA8AGgAA//8AAwAF
    ABAAGwAA//8AAwAGABEAHAAA//8AAwAHABIAHQAA//8AAwAIABMAHgAA//8AAwAJABQAHwAA//8A
    AwAKABUAIAAha2VybgDIa2VybgDQa2VybgDYa2VybgDga2VybgDoa2VybgDwa2VybgD4a2VybgEA
    a2VybgEIa2VybgEQa2VybgEYbWFyawEgbWFyawEobWFyawEwbWFyawE4bWFyawFAbWFyawFIbWFy
    awFQbWFyawFYbWFyawFgbWFyawFobWFyawFwbWttawF4bWttawGAbWttawGIbWttawGQbWttawGY
    bWttawGgbWttawGobWttawGwbWttawG4bWttawHAbWttawHIAAAAAgAAAAEAAAACAAAAAQAAAAIA
    AAABAAAAAgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAA
    AAEAAAACAAAAAQAAAAIAAgADAAAAAgACAAMAAAACAAIAAwAAAAIAAgADAAAAAgACAAMAAAACAAIA
    AwAAAAIAAgADAAAAAgACAAMAAAACAAIAAwAAAAIAAgADAAAAAgACAAMAAAACAAQABQAAAAIABAAF
    AAAAAgAEAAUAAAACAAQABQAAAAIABAAFAAAAAgAEAAUAAAACAAQABQAAAAIABAAFAAAAAgAEAAUA
    AAACAAQABQAAAAIABAAFAAYADgAaACoAMgA6AEIAAgAIAAMAPABOAI4AAgAIAAUA2gQ0CWwJnArM
    AAQAAAABCugABAAAAAELegAGAQAAARlIAAYCAAABGXYAARo4AAQAAAABAAwAAQF+/3QAAhosAAQA
    ABvSHAwABgAEAAD/9gAAAAAAAP/i//b/twAAAAD/yQAAAAAAAP+wAAAAAAAK/7cAAAAAAAD/2AAA
    AAIaCgAEAAAb9BwaAAQACQAA//sAAAAAAAAAAAAAAAAAAAAAAAAACv/7//YAAAAAAAAAAAAAAAr/
    0wAAAAr/9v/7/7f//gAAAAD/8QAAAAAAAAAAAAAAAAABGcYABAAAACMAUABWAFwAYgBoAG4AdAB6
    AIAAhgCMAWoCQAJKAtwC4gLoAu4C9AL6AwADBgMMAxIDGAMeAyQDKgMwAzYDPANCA0gDTgNUAAEA
    bP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/WAAEAbP/W
    ADcAawAPAGwADwBtAA8AbgAPAG8ADwBwAA8AfAAKAH0ACgB+AAoAfwAKAIAACgCBAAoAgwAKAIQA
    CgCFAAoAhgAKAIcACgD3AA8A+AAPAPkADwD6AA8A+wAPAPwADwEIAAoBCQAKAQoACgELAAoBDAAK
    AQ0ACgEPAAoBEAAKAREACgESAAoBEwAKARj/9gEZ//YBbgAAAXD/1QF5AAABewAAAXwAAAGG/9UB
    h//VAYn/1QGK/9UBi//YAYz/9gGN/9gBjv/2AZAAAAGRAAABkgAAAZMAAAHIAAAB0gAAADUAa/+3
    AGz/wQBt/7cAbv+3AG//twBw/7cAfP/XAH3/9AB+//QAf//0AID/9ACB//QAg/+yAIT/sgCF/7IA
    hv+yAIf/sgD3/7cA+P+3APn/twD6/7cA+/+3APz/twEI/9cBCf/0AQr/9AEL//QBDP/0AQ3/9AEP
    /7IBEP+yARH/sgES/7IBE/+yAW7/7AFw/9UBef/dAXv/1QF8/9UBhv/VAYf/1QGJ/9UBiv/VAYv/
    7AGMAAABjf/sAY4AAAGQ/9UBkf/VAZL/1QGT/9UByP/sAdL/7AACAGz//AF+/90AJAAE/9YABf/W
    AAb/1gAH/9YACP/WAAn/1gAK/9YAC//WAAz/1gAN/9YADv+8AA//vACM/9YAjf/WAI7/1gCP/9YA
    kP/WAJH/1gCS/9YAk//WAJT/1gCV/9YAlv+8AJf/vAFw//EBcv/xAX3/8QGG//EBh//xAYn/8QGK
    //EBi//2AYz/8QGN//YBjv/xAcH/+wABAGz/1gABAGz/1gABAGz/1gABAGz/1gABAGz/1gABAGz/
    1gABAGz/1gABAGz/1gABAGz/1gABAGz/1gABAGz/8QABAGz/+wABAGz/+wABAGz/8QABAGz/8QAB
    AGz/8QABAGz/8QABAGz/8QABAGz/9gABAGz/8QABAGz/9gACFrIABAAAGMwaDgAWAB4AAAAFAAX/
    /v/9/9L//v/k//IAAv/SAAQACv/2/+z/9v/uAAoACv/s/9D/y//L/+L/0//7/+IACgAAAAAAAAAA
    //sAAAAAAAAAAP/8////+f/wAAAAAAAAAAAAAAAAAAAAAAAAAAD/+v/6AAAAAAAAAAAAAAAAAAAA
    AAAA//8AAgACAAAAAAAAAAD/+f/3AAAAAAAAAAAABQAFAAAAAAAAAAAAAAAAAAUABQAFAAUAAAAA
    AAAAAAAAAAAAAAACAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAoABQAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAP/g/7oAAAAAAAoAAAAFAAUAAAAAAAAAAP/7AAAAAAAKAA//t//7AAUACgAKAAoACv/7
    AAX/4v/NAAAAAAAA//kAAAAAAAAAAAAAAAD/8//xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAA//sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAP/+//IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gAAAAAA
    AAAAAAAAAAAAAAD/9gAAAAAAAAAAAAD/8P/5AAD//wAAAAAAAAAAAAAABf/i/87/5//2AAUABf/d
    /+wAAAAA//v/7P/4//YAAAAA//sAAAAEAAT//AAA/7IAAP/S/+8AAP+oAAAACv/2/8T/2P/iAA8A
    Cv+3/7f/t/+3/8T/nAAA/9MACgAKAAoAAP/+//YAAAAA//wAAP/+AAD/8P/uAAAAAAAAAAAAAAAA
    AAD/+gAAAAAAAP/6AAAAAAAAAAAAAP/8AAAAAP/d/7gAAAAEAAIAAAAAAAD/9P/7//4AAAAFAAoA
    CgAFAAD/owAAAAAAAAAAAAoACgAAAAr/v//HAAAAAAAAAAAAAAAA//4AAP/8//4AAP/wAAAABQAA
    AAAAAAAAAAAABQAAAAAAAP/7AAAAAAAAAAAACgAAAAAAAP/9//sAAAAAAAAAAAAAAAD/+v/6AAAA
    AAAAAAAAAAAFAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/S/7f//AAAAAoAAAAEAAQAAAAE
    AAD/3f/2/87/4gAKAA//t/+3AAAACgAKAAoACv/nAAX/0//NAAAAAP/+//EAAAAAAAAAAAAAAAD/
    /wAAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAD/9gAAAAAAAP/k/8r//gAAAAQAAAAF
    AAUAAAAAAAD/8f/2/+wAAAAAAAr/y//sAAAACgAKAAoAAP/2AAD/5//Q//sAAP/y/94AAAAAAAQA
    AAAFAAUAAAAAAAD/+wAA//sAAAAAAAr/5//4AAAACgAKAAoAAP/7AAAAAP/rAAAAAAACAAD/8P/6
    AAD//wAAAAAAAAAAAAAABf/i/87/5//2AAUABf/d/+wAAAAA//v/7P/4//YACgAA//sAAP/S/7L/
    7v/wAAQAAAAAAAAAAAAAAAD/2P/i/87/4v/7AAr/o//O/+wACgAKAAD/9v/Y//b/yf/G/+wAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAUACgAA//YAAAAAAAAACv/xAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AP/r/84AAAAA/+QAAP/4//7/1//d/9oAAAAKAAoACgAF/+z/wQAIAAD//v/2AAoAAAAAAAAAAP/M
    AAAAAhHAAAQAABY8FkQAAgAIAAAABQAEAAoADwAKAAoACgAAAAUABAAK/7D/1f/v/7IAAhGYAAQA
    ABZsFr4ADAAMAAAACgAKAAX/3f/n//sABf/YAAoAAAAAAAD/9v/s/+f/4gAAAAD/5//iAAAAAAAA
    AAD/7P/T/9P/zv/s//v/zv/O//YAAAAAAAAACgAKAAoADwAKAAoABQAKAAAAAAAAAAAACgAKAAX/
    t//L/+cABf+jAAr/+v/+AAD/7P/T/8H/t//s//j/3f/O//EAAAAAAAD/0P+t/7cAAAAKAAoAAAAK
    AAAAAAAAAAD/y/+j/7cACgAKAAoAAAAKAAD/+AAAAAD/y/+j/7cACgAKAAoAAAAKAAD/+gAAAAD/
    0/+r/8QACgAAAAD/7P/2AAAAAAAAAAAAAAAAAAD/0//i//YAAP/OAAAAAAAAAAD/5//J/9MACgAK
    AAoAAAAFAAAAAAAAAAIQogAEAAAWOhZCAAIABwAA//b/8wAAAAAAAAAAAAAAAP/x//H/2P/2/+wA
    ARB+EI4AAgAMAEYADgABAFIAAQBSAAEAUgABAFIAAQBYAAEAUgABAFIAAQBSAAEAUgABAFIAAQBS
    AAEAUgAAAEwAAABMAAQAJAAqADAANgA8AEIASABOAAEAAAAAAAEAAAK8AAEABAK8AAEAuQAAAAEA
    sgK8AAEApAAAAAEApAK8AAEB3QAAAAEB3QK8AAEAxwAAAAEAwgK8AAEQABAKAAUADABeABQAAgri
    AAIK4gACCuIAAgriAAIK6AAECuIAAgriAAIK4gACCuIAAgriAAIK4gACCuIAAgriAAAK1gAACtYA
    AQrcAAMK7gADCu4AAwruAAMK7gENCqIKqAquDXINcgqiCqgKtA1yDXIKogqoCrQNcg1yCqIKqAq0
    DXINcgqiCqgKug1yDXIKogqoCrQNcg1yCqIKqArADXINcgqiCqgKrg1yDXIKogqoCsYNcg1yCqIK
    qArMDXINcgrSDXIK2A1yDXIK0g1yCt4Ncg1yCuQNcgrqDXINcgrkDXIK8A1yDXIK9g1yCvwNcg1y
    CvYNcgsCDXINcgr2DXILAg1yDXILCA1yCvwNcg1yCvYNcgsCDXINcgr2DXILDg1yDXILFA1yCyAL
    Gg1yCyYNcgsyCywNcgsUDXILOAsaDXILJg1yCzILLA1yCxQNcgs+CxoNcgtEC0oK6g1yDXILRAtK
    C1ANcg1yC0QLSgtQDXINcgtEC0oLUA1yDXILRAtKC1ANcg1yC0QLSgrwDXINcgtEC0oK8A1yDXIL
    RAtKC1ANcg1yC0QLSgtWDXINcgtEC0oK6g1yDXILXA1yC2INcg1yC1wNcgtoDXINcgtuDXILdA1y
    DXILbg1yC3oNcg1yC24Ncgt6DXINcguADXILdA1yDXILbg1yC4YNcg1yC4wNcguYC5INcgueDXIL
    qgukDXILjA1yC7ALkg1yC7YLvAvCDXINcgvIC7wLzg1yDXILtgu8C9QNcg1yC7YLvAvUDXINcgu2
    C7wL1A1yDXILtgu8C9oNcg1yC7YLvAvaDXINcgu2C7wL1A1yDXILtgu8C+ANcg1yC7YLvAvCDXIN
    cgu2C7wL5g1yDXIL7A1yC/INcg1yC+wNcgv4DXINcgvsDXIL+A1yDXIL/g1yDAQNcg1yDAoNcgwE
    DXINcgwQDXIMHAwWDCIMEA1yDCgMFgwiDBANcgwcDBYMIgwuDXIMHAwWDCIMEA1yDBwMFgwiDDQN
    cgxADDoMRgxMDXIMUg1yDXIMTA1yDFgNcg1yDF4NcgxkDXINcgxeDXIMag1yDXIMXg1yDGoNcg1y
    DHANcgxkDXINcgxeDXIMZA1yDXIMXg1yDHYNcg1yDHwMiAyODIIMlAx8DIgMmgyCDJQMfAyIDJoM
    ggyUDHwMiAyaDIIMlAx8DIgMoAyCDJQMfAyIDJoMggyUDHwMiAyaDIIMlAx8DIgMpgyCDJQMfAyI
    DI4MggyUDHwMiAyaDIIMlAx8DIgMrAyCDJQMsg1yCuoNcg1yDLINcgrwDXINcgy4DXIK/A1yDXIM
    uA1yCwINcg1yDLgNcgsCDXINcgy+DXIK/A1yDXIMxA1yDMoNcg1yDMQNcgzQDXINcgzEDXIM0A1y
    DXIM1g1yDMoNcg1yDMQNcgzQDXINcgzcDXIMyg1yDXIMxA1yDOINcg1yDOgNcgz0DO4NcgzoDXIM
    9AzuDXIM6A1yDPoM7g1yDQANcgz0DO4Ncg0GDXIM9AzuDXIM6A1yDQwM7g1yCqINEgquDXINGAqi
    DRIKtA1yDRgKog0SCrQNcg0YCqINEgq0DXINGAqiDRIKug1yDRgKog0SCrQNcg0YCqINEgq0DXIN
    GAqiDRIKwA1yDRgKog0SCq4Ncg0YCqINEgrGDXINGAqiDRIKzA1yDRgNHg1yCuoNcg1yDSQNcg0q
    DXINcg0kDXINMA1yDXINJA1yDTANcg1yDSQNcg02DXINcg0kDXINMA1yDXIMuA1yDTwNcg1yCvYN
    cgt0DXINcgr2DXILeg1yDXIK9g1yC3oNcg1yCvYNcguGDXINcgr2DXILeg1yDXINQg1yDUgNcg1y
    DUINcg1ODXINcg1CDXINTg1yDXINQg1yDVQNcg1yCqIKqAquDXINcgqiCqgKtA1yDXIKogqoCrQN
    cg1yCqIKqAq0DXINcgqiCqgKug1yDXIKogqoCrQNcg1yCqIKqArADXINcgqiCqgKrg1yDXIKogqo
    CsYNcg1yCqIKqArMDXINcgrSDXIK2A1yDXIK0g1yCt4Ncg1yCuQNcgrqDXINcgrkDXIK8A1yDXIK
    9g1yCvwNcg1yCvYNcgsCDXINcgr2DXILAg1yDXILCA1yCvwNcg1yCvYNcgsCDXINcgr2DXILDg1y
    DXILFA1yCyALGg1yCyYNcgsyCywNcgsUDXILOAsaDXILJg1yCzILLA1yCxQNcgs+CxoNcgtEC0oK
    6g1yDXILRAtKC1ANcg1yC0QLSgtQDXINcgtEC0oLUA1yDXILRAtKC1ANcg1yC0QLSgrwDXINcgtE
    C0oK8A1yDXILRAtKC1ANcg1yC0QLSgtWDXINcgtEC0oK6g1yDXILXA1yC2INcg1yC1wNcgtoDXIN
    cgtuDXILdA1yDXILbg1yC3oNcg1yC24Ncgt6DXINcguADXILdA1yDXILbg1yC4YNcg1yC4wNcguY
    C5INcgueDXILqgukDXILjA1yC7ALkg1yC7YLvAvCDXINcgu2C7wLwg1yDXILtgu8C9QNcg1yC7YL
    vAvUDXINcgu2C7wL1A1yDXILtgu8C9oNcg1yC7YLvAvaDXINcgu2C7wL1A1yDXILyAu8C84Ncg1y
    C7YLvAvgDXINcgu2C7wLwg1yDXILtgu8C+YNcg1yC+wNcgvyDXINcgvsDXIL8g1yDXIL7A1yC/gN
    cg1yC+wNcgv4DXINcgv+DXIMBA1yDXIMCg1yDAQNcg1yC/4NcgwEDXINcgwQDXIMHAwWDCIMEA1y
    DCgMFgwiDBANcgwcDBYMIgwuDXIMHAwWDCIMEA1yDBwMFgwiDDQNcgxADDoMRgxMDXIMUg1yDXIM
    TA1yDFgNcg1yDF4NcgxkDXINcgxeDXIMag1yDXINWg1yDWANcg1yDF4NcgxqDXINcgxwDXIMZA1y
    DXIMXg1yDGQNcg1yDF4Ncgx2DXINcgx8DIgMjgyCDJQMfAyIDJoMggyUDHwMiAyaDIIMlAx8DIgM
    mgyCDJQMfAyIDKAMggyUDHwMiAyaDIIMlAx8DIgMmgyCDJQMfAyIDKYMggyUDHwMiAyODIIMlAx8
    DIgMmgyCDJQMfAyIDKwMggyUDLINcgrqDXINcgyyDXIK8A1yDXIMuA1yCvwNcg1yDLgNcgsCDXIN
    cgy4DXILAg1yDXIMvg1yCvwNcg1yDMQNcgzKDXINcgzEDXIM0A1yDXIMxA1yDNANcg1yDNYNcgzK
    DXINcgzEDXIM0A1yDXIM3A1yDMoNcg1yDMQNcgziDXINcgzoDXIM9AzuDXIM6A1yDPQM7g1yDOgN
    cgz6DO4Ncg0ADXIM9AzuDXINBg1yDPQM7g1yDOgNcg0MDO4NcgqiDRIKrg1yDRgKog0SCrQNcg0Y
    CqINEgq0DXINGAqiDRIKtA1yDRgKog0SCroNcg0YCqINEgq0DXINGAqiDRIKtA1yDRgKog0SCsAN
    cg0YCqINEgquDXINGAqiDRIKxg1yDRgKog0SCswNcg0YDR4NcgrqDXINcg0kDXINKg1yDXINJA1y
    DTANcg1yDSQNcg0wDXINcg0kDXINNg1yDXINJA1yDTANcg1yDLgNcg08DXINcgr2DXILdA1yDXIK
    9g1yC3oNcg1yCvYNcgt6DXINcgr2DXILhg1yDXIK9g1yC3oNcg1yDUINcg1IDXINcg1CDXINTg1y
    DXINQg1yDU4Ncg1yDUINcg1UDXINcg1mDXINbA1yDXIAAQAAAAAAAQBOAAAAAQAAArwAAQAEArwA
    AQAAAV4AAQDJAAAAAQGFAAAAAQDJArwAAQDJA14AAQDJA1EAAQDJAz0AAQDJA5AAAQDJA2IAAQEg
    AAAAAQEgArwAAQEgA14AAQDKAAAAAQC/ArwAAQC/A1EAAQDFAAAAAQDBArwAAQDBA14AAQDF/20A
    AQDBA1EAAQDMAAAAAQBlAWgAAQDDArwAAQDdAAAAAQB2AWgAAQDUArwAAQDDA14AAQDDA1EAAQC0
    AAAAAQFVAAAAAQC/A14AAQC/Az0AAQCsAAAAAQC3ArwAAQC3A1EAAQDEAAAAAQDFArwAAQDFA14A
    AQDE/0MAAQDFA1EAAQDSAAAAAQDSAh4AAQDSArwAAQDbAAAAAQDbAh4AAQDbArwAAQDSA14AAQBg
    AAAAAQCtAAAAAQBgArwAAQFHAAAAAQFdArwAAQBgA14AAQBgA1EAAQBgAz0AAQBgA2IAAQCHAAAA
    AQCdArwAAQCdA14AAQDZAAAAAQDPArwAAQDZ/0MAAQC7AAAAAQCsAV4AAQBqArwAAQEEArwAAQBq
    A14AAQC7/0MAAQDPAAAAAQDAAV4AAQB+ArwAAQEYArwAAQENAAAAAQENArwAAQENA1EAAQDWAAAA
    AQDWArwAAQDWA14AAQDW/0MAAQDWA2IAAQDIAAAAAQDIAV4AAQFnAAoAAQDIArwAAQF7ArwAAQDI
    A14AAQDIA1EAAQDIAz0AAQDIA2IAAQDBAAAAAQDLAAAAAQDL/0MAAQC6AAAAAQC6ArwAAQC6A14A
    AQC6/20AAQC6/0MAAQC6A1EAAQC2AAAAAQC2AV4AAQC2ArwAAQC2A14AAQC2/20AAQC2/0MAAQC2
    A1EAAQEpAAAAAQF9ArwAAQC/AAAAAQEXAAAAAQEXArwAAQEXA14AAQEXA1EAAQDLArwAAQC1AAAA
    AQC5ArwAAQC5A14AAQC5A1EAAQFJAAAAAQFJArwAAQC9AAAAAQC4ArwAAQAAAAAAAQJoAnAAAQAM
    ABYAAgAAABIAAAASAAMADgAUABoAAQAAAAAAAQAA/0MAAQAA/20AAQD//20AAQJEAlQAAQAMAD4A
    DAAAAGQAAABkAAAAZAAAAGQAAABqAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAYAD4APgBE
    AEQASgBEAEQARABQAFYAXABiAGgAbgBuAG4AbgB0AHQAbgB6AGgAgACGAAEAAAK8AAEABAK8AAEA
    AANRAAEAAANeAAEABANeAAEAAAOQAAEAAANiAAEAAAM9AAEAAANLAAEA+gM9AAEA+gNeAAEA+gNR
    AAEA/gNeAAEA+gOQAAEA+gNiAAEAAQF+AAEADQFuAXIBcwF0AXgBewF8AX0BjwGQAZEBkgGTAAEA
    CAEqASwBLQEvATQBNgE3ATkAAgALAAQADQAAAEMAQwAKAEYARgALAF0AXQAMAGwAbAANAIwAlQAO
    AXABcAAYAXIBcgAZAX0BfQAaAYYBhwAbAYkBjgAdAAIACwAEAC0AAAAyADIAKgA8ADwAKwA+AEQA
    LABGAEYAMwBPALUANADBAMEAmwDJAM0AnADPAM8AoQDbAOgAogDqARcAsAABAAIAzgDRAAEAGwFu
    AXABcgFzAXQBeAF6AXsBfAF9AX4BgAGCAYQBhgGHAYkBigGLAYwBjQGOAY8BkAGRAZIBkwABAAIB
    wQHCAAIAAgHTAdcAAAHZAeEABQABAAQBuQHQAdIB9wACAAEB0wHmAAAAAgAIAAQAWQAAAFsAXABW
    AF8AaQBYAGsA5QBjAOcA6ADeAOsA9QDgAPcBFwDrAZ8BnwEMAAEAAgHgAeEAAQADAeAB4QHsAAIA
    AgHTAdcAAAHZAd8ABQACAAUB0wHXAAAB2QHfAAUB6AHrAAwB7QHyABAB9AH1ABYAAgAJAW4BbgAF
    AXMBdAABAXgBeAABAXsBfAAEAY8BjwABAZABkAACAZEBkQADAZIBkgACAZMBkwADAAIABgEpASkA
    AwEsASwAAgEvAS8AAQEzATMAAwE2ATYAAgE5ATkAAQABASoAEAADAAAAAQAAAAAAAgAAAAAAAAAA
    AAMAAAABAAAAAAACAAIAEAEoASgACAEpASkAAwEsASwAAgEtAS0ABgEvAS8AAQEyATIACAEzATMA
    AwE2ATYAAgE3ATcABgE5ATkAAQFyAXIABQFzAXQABwF4AXgABwF7AXwABAF9AX0ABQGPAY8ABwAC
    ADUADgAPAAMAEAARAAEAEgAXAAIAGAAcAAoAHQAmAAMAJwAoAAQAKQAtAAUAMgAyAAcAPAA8AAcA
    PgA+AAcAPwBAAAgAQQBEAAkARgBGAAkATwBZAAoAWgBaAAMAWwBcAAsAXQBdABUAXgBeAAoAXwBi
    AAwAYwBpAA0AagBqAAYAawBwAA4AcQB7AA8AfAB8ABAAfQCBABEAggCCABIAgwCHABMAiACLABQA
    lgCXAAMAmACZAAEAmgCfAAIAoACkAAoApQCuAAMArwCwAAQAsQC1AAUAwQDBAAcAyQDLAAgAzADN
    AAkAzwDPAAkA2wDlAAoA5gDmAAMA5wDoAAsA6gDqAAoA6wDuAAwA7wD1AA0A9gD2AAYA9wD8AA4A
    /QEHAA8BCAEIABABCQENABEBDgEOABIBDwETABMBFAEXABQAAgA7AAQADQABAA4ADwACABIAFwAD
    ACkALQADADwAPAAcAD4APgAcAE8AWgADAF4AXgADAGMAaQAEAGsAcAAFAHEAewAGAHwAfAAHAH0A
    gQAIAIIAggAJAIMAhwAKAIgAiwALAIwAlQABAJYAlwACAJoAnwADALEAtQADANsA5gADAOoA6gAD
    AO8A9QAEAPcA/AAFAP0BBwAGAQgBCAAHAQkBDQAIAQ4BDgAJAQ8BEwAKARQBFwALARgBGQAQAW4B
    bgAYAXABcAATAXIBcgAMAXMBdAASAXgBeAASAXkBeQAaAXsBfAAWAX0BfQAMAX4BfgAbAYEBgQAR
    AYMBgwARAYUBhQARAYYBhwATAYkBigATAYsBiwAOAYwBjAAPAY0BjQAOAY4BjgAPAY8BjwASAZAB
    kAAUAZEBkQAVAZIBkgAUAZMBkwAVAcEBwQAZAcIBwgAdAcUBxwANAcgByAAXAdIB0gAXAAEA0QAB
    AAEAAgAOAAQADQABAA4ADwACADwAPAADAD4APgADAGsAcAAEAHwAfAAFAH0AgQAGAIMAhwAHAIwA
    lQABAJYAlwACAPcA/AAEAQgBCAAFAQkBDQAGAQ8BEwAHAAEBbgAmAAkAAAAFAAAAAAAEAAQAAAAA
    AAAABAAAAAoACAAIAAAACwAAAAMAAAADAAAAAwAAAAUABQAAAAUABQABAAIAAQACAAQABgAHAAYA
    BwACABwABAANAAEADgAPAAIAEgAXAAoAKQAtAAoAPAA8AAMAPgA+AAMATwBaAAoAXgBeAAoAawBw
    AAQAcQB7AAsAfAB8AAUAfQCBAAYAggCCAAcAgwCHAAgAiACLAAkAjACVAAEAlgCXAAIAmgCfAAoA
    sQC1AAoA2wDmAAoA6gDqAAoA9wD8AAQA/QEHAAsBCAEIAAUBCQENAAYBDgEOAAcBDwETAAgBFAEX
    AAkAAQHBAAEAAQACAAwABAANAAMADgAPAAQAPAA8AAUAPgA+AAUAawBwAAEAggCCAAYAgwCHAAIA
    jACVAAMAlgCXAAQA9wD8AAEBDgEOAAYBDwETAAIAAAABAAAACgGGB3QAAkRGTFQADmxhdG4ALAAE
    AAAAAP//AAoAAAALABYAIQA1AEAASwBWAGEAbAA6AAlBWkUgAFRDQVQgAHBDUlQgAIxLQVogAKhN
    T0wgAMROTEQgAOBST00gAPxUQVQgARhUUksgATQAAP//AAoAAQAMABcAIgA2AEEATABXAGIAbQAA
    //8ACwACAA0AGAAjACwANwBCAE0AWABjAG4AAP//AAsAAwAOABkAJAAtADgAQwBOAFkAZABvAAD/
    /wALAAQADwAaACUALgA5AEQATwBaAGUAcAAA//8ACwAFABAAGwAmAC8AOgBFAFAAWwBmAHEAAP//
    AAsABgARABwAJwAwADsARgBRAFwAZwByAAD//wALAAcAEgAdACgAMQA8AEcAUgBdAGgAcwAA//8A
    CwAIABMAHgApADIAPQBIAFMAXgBpAHQAAP//AAsACQAUAB8AKgAzAD4ASQBUAF8AagB1AAD//wAL
    AAoAFQAgACsANAA/AEoAVQBgAGsAdgB3YWFsdALMYWFsdALUYWFsdALcYWFsdALkYWFsdALsYWFs
    dAL0YWFsdAL8YWFsdAMEYWFsdAMMYWFsdAMUYWFsdAMcY2NtcAMkY2NtcAMqY2NtcAMwY2NtcAM2
    Y2NtcAM8Y2NtcANCY2NtcANIY2NtcANOY2NtcANUY2NtcANaY2NtcANgZG5vbQNmZG5vbQNsZG5v
    bQNyZG5vbQN4ZG5vbQN+ZG5vbQOEZG5vbQOKZG5vbQOQZG5vbQOWZG5vbQOcZG5vbQOiZnJhYwOo
    ZnJhYwOyZnJhYwO8ZnJhYwPGZnJhYwPQZnJhYwPaZnJhYwPkZnJhYwPuZnJhYwP4ZnJhYwQCZnJh
    YwQMbG9jbAQWbG9jbAQcbG9jbAQibG9jbAQobG9jbAQubG9jbAQ0bG9jbAQ6bG9jbARAbG9jbARG
    bnVtcgRMbnVtcgRSbnVtcgRYbnVtcgRebnVtcgRkbnVtcgRqbnVtcgRwbnVtcgR2bnVtcgR8bnVt
    cgSCbnVtcgSIb3JkbgSOb3JkbgSWb3JkbgSeb3JkbgSmb3JkbgSub3JkbgS2b3JkbgS+b3JkbgTG
    b3JkbgTOb3JkbgTWb3JkbgTecG51bQTmcG51bQTscG51bQTycG51bQT4cG51bQT+cG51bQUEcG51
    bQUKcG51bQUQcG51bQUWcG51bQUccG51bQUic3VicwUoc3VicwUuc3VicwU0c3VicwU6c3VicwVA
    c3VicwVGc3VicwVMc3VicwVSc3VicwVYc3VicwVec3VicwVkc3VwcwVqc3VwcwVwc3VwcwV2c3Vw
    cwV8c3VwcwWCc3VwcwWIc3VwcwWOc3VwcwWUc3VwcwWac3VwcwWgc3VwcwWmdG51bQWsdG51bQWy
    dG51bQW4dG51bQW+dG51bQXEdG51bQXKdG51bQXQdG51bQXWdG51bQXcdG51bQXidG51bQXoAAAA
    AgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAgAAAAEAAAAC
    AAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAQAAAAEAAgAAAAEAAgAAAAEAAgAAAAEAAgAAAAEA
    AgAAAAEAAgAAAAEAAgAAAAEAAgAAAAEAAgAAAAEAAgAAAAEAAgAAAAEAEAAAAAEAEAAAAAEAEAAA
    AAEAEAAAAAEAEAAAAAEAEAAAAAEAEAAAAAEAEAAAAAEAEAAAAAEAEAAAAAEAEAAAAAMAEQASABMA
    AAADABEAEgATAAAAAwARABIAEwAAAAMAEQASABMAAAADABEAEgATAAAAAwARABIAEwAAAAMAEQAS
    ABMAAAADABEAEgATAAAAAwARABIAEwAAAAMAEQASABMAAAADABEAEgATAAAAAQALAAAAAQAEAAAA
    AQAKAAAAAQAHAAAAAQAGAAAAAQADAAAAAQAFAAAAAQAIAAAAAQAJAAAAAQAPAAAAAQAPAAAAAQAP
    AAAAAQAPAAAAAQAPAAAAAQAPAAAAAQAPAAAAAQAPAAAAAQAPAAAAAQAPAAAAAQAPAAAAAgAUABUA
    AAACABQAFQAAAAIAFAAVAAAAAgAUABUAAAACABQAFQAAAAIAFAAVAAAAAgAUABUAAAACABQAFQAA
    AAIAFAAVAAAAAgAUABUAAAACABQAFQAAAAEADAAAAAEADAAAAAEADAAAAAEADAAAAAEADAAAAAEA
    DAAAAAEADAAAAAEADAAAAAEADAAAAAEADAAAAAEADAAAAAEADQAAAAEADQAAAAEADQAAAAEADQAA
    AAEADQAAAAEADQAAAAEADQAAAAEADQAAAAEADQAAAAEADQAAAAEADQAAAAEADgAAAAEADgAAAAEA
    DgAAAAEADgAAAAEADgAAAAEADgAAAAEADgAAAAEADgAAAAEADgAAAAEADgAAAAEADgAAAAEAFgAA
    AAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEAFgAAAAEA
    FgAbADgAQABIAFIAXABmAG4AdgB+AIYAjgCWAJ4ApgCuALYAvgDGAM4A1gDgAOoA8gD6AQIBCgES
    AAEAAAABAmoAAwAAAAECkAAGAAAAAgDSAOQABgAAAAIA7gEAAAYAAAACAQgBHAABAAAAAQEmAAEA
    AAABASwAAQAAAAEBMgABAAAAAQEwAAEAAAABAS4AAQAAAAEBLAABAAAAAQEqAAEAAAABASgAAQAA
    AAEBTgABAAAAAQFMAAEAAAABAUoAAQAAAAEBSAABAAAAAQFGAAEAAAABAUQABgAAAAIBQgFUAAYA
    AAACAVwBbgAEAAAAAQF2AAEAAAABAYIAAQAAAAEDBAABAAAAAQMCAAQAAAABAwQAAQAAAAEDGgAD
    AAAAAQM0AAEDPAABAAAAFwADAAAAAQMiAAIDOgMqAAEAAAAXAAMAAQMwAAEDNgAAAAEAAAAYAAMA
    AQMqAAEDMAAAAAEAAAAYAAMAAAACAyQDKgABAyQAAQAAABkAAwAAAAIDHAMWAAEDHAABAAAAGQAC
    Aw4ABABoAG8A9AD7AAIDAAAEAGgAbwD0APsAAQL+AAYAAQL4AAYAAQLyAAYAAQLsAAYAAQLmAAYA
    AgLmABQBMgEzATQBNQE2ATcBOAE5AToBOwEyATMBNAE1ATYBNwE4ATkBOgE7AAECwgAeAAECvAA8
    AAECtgAyAAECsAAoAAECtP/mAAECpAAyAAMAAQKuAAECtAAAAAEAAAAaAAMAAQKsAAECogAAAAEA
    AAAaAAMAAQJ6AAECpAAAAAEAAAAaAAMAAQJoAAECmgAAAAEAAAAaAAECkAABAAgAAQAEAdAAAwDb
    AXgAAgKCABQBHgEfASABIQEiASMBJAElASYBJwEeAR8BIAEhASIBIwEkASUBJgEnAAICXgAUARgA
    PQEZAGgAbwEYARkA9AD7AUYBRwFIAUkBSgFLAUwBTQFOAU8BZAABAlwAIABGAEwAUgBeAGoAdgCC
    AI4AmgCmALIAvgDKANAA1gDcAOIA6ADuAPQA+gEAAQYBCgEOARIBFgEaAR4BIgEmASoAAgC6AL8A
    AgDGAMcABQEyATwBWgFQAUYABQEzAT0BWwFRAUcABQE0AT4BXAFSAUgABQE1AT8BXQFTAUkABQE2
    AUABXgFUAUoABQE3AUEBXwFVAUsABQE4AUIBYAFWAUwABQE5AUMBYQFXAU0ABQE6AUQBYgFYAU4A
    BQE7AUUBYwFZAU8AAgEyAR4AAgEzAR8AAgE0ASAAAgE1ASEAAgE2ASIAAgE3ASMAAgE4ASQAAgE5
    ASUAAgE6ASYAAgE7AScAAQEeAAEBHwABASAAAQEhAAEBIgABASMAAQEkAAEBJQABASYAAQEnAAEA
    UAABAAIBPgACAD0AxwABATwAAgAKABQAAQAEAEUAAgFwAAEABADQAAIBcAACASYADgEYARkBGAEZ
    AUYBRwFIAUkBSgFLAUwBTQFOAU8AAQACALkAxQACAAIB0wHXAAAB2QHfAAUAAgABAeEB5gAAAAEA
    AQC7AAEAAQDFAAEAAQAzAAEAAQA8AAEAAQDMAAEAAQFwAAEAAQBBAAEABABmAG4A8gD6AAEAAQC5
    AAIAAQEeATEAAAACAAEBHgEnAAAAAQABAX4AAQABAWQAAgABAVABWQAAAAIAAQFGAU8AAAABAAIA
    BACMAAEAAgBPANsAAQABAEkAAgABASgBOwAAAAEAFAAEADwATwBmAG4AjADbAPIA+gFQAVEBUgFT
    AVQBVQFWAVcBWAFZAX4AAgADALkAuQAAAMUAxQABAR4BOwACAAEAAgA8AMUAAQACAEEAzAABAA4A
    BABPAIwA2wFQAVEBUgFTAVQBVQFWAVcBWAFZAAAAAwGCAZAABQAAAooCWAAAAEsCigJYAAABXgBQ
    AaQAAAILBgYCAgIFAgEAAAAHAAAAAQAAAAAAAAAAZGhybQBAAA34/wLu/wYAAAOEASwgAACTAAAA
    AAK8ArwAAAAgAAMAAAADAAAAAwAAAhQAAQAAAAAAHAADAAEAAAIUAAYB+AAAAAkA9wADAAAAAAAA
    AAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwF1AXsBdwGdAb0BwgF8AYQB
    hQFuAaUBcwGJAXgBfgEeAR8BIAEhASIBIwEkASUBJgEnAXIBfQGsAakBqwF5AcEABAAQABIAGAAd
    ACcAKQAuADEAPAA/AEEARwBJAE8AWwBeAF8AYwBrAHEAfAB9AIIAgwCIAYIBbwGDAdEBfwHwAIwA
    mACaAKAApQCvALEAtgC5AMUAyQDMANIA1ADbAOcA6gDrAO8A9wD9AQgBCQEOAQ8BFAGAAcoBgQGx
    AAAACAAMABUAHgBOAFMAdQCNAJEAjwCQAJUAlACdAKYArACpAKoAuwDAAL0AvgDaANwA4ADeAN8A
    5QD+AQIBAAEBAcwByQGbAaEBxAFxAcMA9gHGAcUByAHpAe4BqgAOAFcBswGvAa4BrQGiAbsBvAG5
    AbgBHQG1ARgBGQEbAJYA4wF6AXYBsgG6AZ8BsAG3AYsBjAF0AZkACQANAFkAWgDmAYcBhgGQAZEB
    kgGTAagBvwESAIYBZAGeAY0BjgAAAAABzgFwAZQBjwG+AAcAIQAFACIAJAAzADUANgA4AFAAUgHA
    AFQAcgB0AHYAugHtAfUB8gHqAe8B9AHsAfEB8wHrAAQFcAAAAJQAgAAGABQADQAvAH4BfgGSAf8C
    GwI3ArwCxwLJAt0DBAMIAwwDEgMoAzgDlAOpA7wDwB4DHgseHx5BHlceYR5rHoUenh7zIAMgCCAL
    IBQgGiAeICIgJiAwIDogRCBwIHkgiSCsILkgvyETIRchICEiISYhLiFUIV4iAiIGIg8iEiIVIhoi
    HiIrIkgiYCJlJcrg/+/98AD4////AAAADQAgADAAoAGSAfwCGAI3ArwCxgLJAtgDAAMGAwoDEgMm
    AzUDlAOpA7wDwB4CHgoeHh5AHlYeYB5qHoAenh7yIAIgByALIBIgGCAcICAgJiAwIDkgRCBwIHQg
    gCCsILkgvyETIRYhICEiISYhLiFTIVsiAiIFIg8iESIVIhkiHiIrIkgiYCJkJcrg/+/98AD4////
    //UAAAAAAAAADQAAAAD+j/8rAAD/HwAAAAAAAAAA/s3+uv6u/Yb9cv1g/V0AAAAAAAAAAAAAAAAA
    AAAA4cwAAAAA4ZDhjwAA4XoAAAAA4U7hjuFU4SDg6uDq4Lzg8uDn4TjgugAA4LLgpuCQ4KHgE+AP
    37oAAN+pAADfjwAA35Xfit9o30oAANv1AAAAAAAAAAAAAQAAAJIAsAFMAAADBgMMAAAAAAMOAAAD
    DgMYAyADJAAAAAAAAAAAAAAAAAAAAxoDHAMeAyADIgMkAyYDKAAAAzADMgAAAAADMAAAAzIDNgAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAADJAAAAAAAAAAAAAAAAAAAAxgAAAMYAAADGAAAAAAAAAAAAxIA
    AAMSAxIDEgMSAAAAAwF1AXsBdwGdAb0BwgF8AYQBhQFuAaUBcwGJAXgBfgEeAR8BIAEhASIBIwEk
    ASUBJgEnAXIBfQGsAakBqwF5AcEABAAQABIAGAAdACcAKQAuADEAPAA/AEEARwBJAE8AWwBeAF8A
    YwBrAHEAfAB9AIIAgwCIAYIBbwGDAdEBfwHwAIwAmACaAKAApQCvALEAtgC5AMUAyQDMANIA1ADb
    AOcA6gDrAO8A9wD9AQgBCQEOAQ8BFAGAAcoBgQGxAZkBdgGbAaEBnAGiAcsBxAHuAcUBGAGLAbIB
    igHGAfIByQGvAVwBXQHpAbsBwwFwAewBWwEZAYwBaAFlAWkBegAJAAUABwANAAgADAAOABUAJAAe
    ACEAIgA4ADMANQA2ABkATgBUAFAAUgBZAFMBpwBXAHYAcgB0AHUAhABdAPYAkQCNAI8AlQCQAJQA
    lgCdAKwApgCpAKoAwAC7AL0AvgChANoA4ADcAN4A5QDfAagA4wECAP4BAAEBARAA6QESAAoAkgAG
    AI4ACwCTABMAmwAWAJ4AFwCfABQAnAAaAKIAGwCjACUArQAfAKcAIwCrACYArgAgAKgAKwCzACoA
    sgAtALUALAC0ADAAuAAvALcAOwDEADkAwgA0ALwAOgDDADcAugAyAMEAPgDIAEAAygDLAEIAzQBE
    AM8AQwDOAEUA0ABGANEASgDVAEwA2ABLANcA1gBNANkAVgDiAFEA3QBVAOEAWgDmAGAA7ABiAO4A
    YQDtAGQA8ABnAPMAZgDyAGUA8QBuAPoAbQD5AGwA+AB7AQcAeAEEAHMA/wB6AQYAdwEDAHkBBQB/
    AQsAhQERAIYAiQEVAIsBFwCKARYADwCXAFgA5ABoAPQAbwD7Ae0B6wHqAe8B9AHzAfUB8QHVAdYB
    2QHdAd4B2wHUAdMB3AHXAdoAEQCZABwApAAoALAASADTAFwA6ABpAPUAcAD8AIEBDQB+AQoAgAEM
    AIcBEwGWAZUBiAGHAYYBkAGRAY8BzAHOAXEB0AHHAbQBtwG5AaYBowG6Aa4BrQH4AfkB+gHAAAUA
    NgAAAqwCvAADAAYACQAMAA8ANUAyDgwLCgkIBgcDAgFKAAAAAgMAAmUEAQMBAQNVBAEDAwFdAAED
    AU0NDQ0PDQ8RERAFChcrEyERIQEhEwcDEQEDEwcDAzYCdv2KAiP+MOgh6AIS6Ogh6OgCvP1EAor+
    +SUBB/3yAg7++f75JQEH/vkAAAACAAwAAAGFArwACAAMACtAKAoBBAABSgUBBAACAQQCZgAAABdL
    AwEBARgBTAkJCQwJDBEhERAGBxgrEzMTIycVIwcjNwMjA36Vcm4UfRRm6jECMAK8/USLAonoAVr+
    pv//AAwAAAGFA14AIgAEAAAAAwHWAMkAAP//AAwAAAGFA14AIgAEAAAAAwHbAMkAAP//AAwAAAGF
    A14AIgAEAAAAAwHZAMkAAP//AAwAAAGFA1EAIgAEAAAAAwHTAMkAAP//AAwAAAGFA14AIgAEAAAA
    AwHVAMkAAP//AAwAAAGFA0IAIgAEAAAAAwHeAMkAAP//AAz/bQGFArwAIgAEAAAAAwHiATcAAP//
    AAwAAAGFA5AAIgAEAAAAAwHcAMkAAP//AAwAAAGFA2IAIgAEAAAAAwHdAMkAAAACAAoAAAIuArwA
    DwATAEFAPhEBAgEBSgACAAMIAgNlCQEIAAYECAZlAAEBAF0AAAAXSwAEBAVdBwEFBRgFTBAQEBMQ
    ExEREREREREQCgccKxMhFSMVMxUjFTMVITUjByM3ESMDxQFpvpeXvv7UbCNp+AJSArxkuWTXZImJ
    6AFN/rMAAP//AAoAAAIuA14AIgAOAAAAAwHWASAAAAADACkAAAF9ArwAEAAaACQAPUA6CAEFAgFK
    BgECAAUEAgVnAAMDAF0AAAAXSwcBBAQBXQABARgBTBwbEhEjIRskHCQZFxEaEhosIAgHFisTMzIW
    FRUUBgcVFhUVFAYjIxMyNjU1NCYjIxUTMjY1NTQmIyMVKaZVTiMkUlVSrZkhIRsdNT8dHCEmMQK8
    T1IcNkQPAhx2PFFVAZ8iKCcmIrn+xR8mPTAl1///ACkAAAF9A1EAIgAQAAAAAwHUAL8AAAABACL/
    9gFmAsYAGwBlS7AJUFhAJAABAgQCAXAABAMCBAN8AAICAF8AAAAdSwADAwVgBgEFBR4FTBtAJQAB
    AgQCAQR+AAQDAgQDfAACAgBfAAAAHUsAAwMFYAYBBQUeBUxZQA4AAAAbABoSIyITJQcHGSsWJjUR
    NDYzMhYVFSM1NCMiFREUMzI1NTMVFAYjdVNTT09TaDc3NzdoU08KWlIBeFJaWlJKUUFB/nlAQGtj
    UloAAP//ACL/9gFmA14AIgASAAAAAwHWAMEAAP//ACL/9gFmA14AIgASAAAAAwHaAMEAAP//ACL/
    bQFmAsYAIgASAAAAAwHhAMUAAP//ACL/9gFmA14AIgASAAAAAwHZAMEAAP//ACL/9gFmA1EAIgAS
    AAAAAwHUAMEAAAACACkAAAF1ArwACQATACZAIwADAwBdAAAAF0sEAQICAV0AAQEYAUwLChIQChML
    EyUgBQcWKxMzMhYVERQGIyM3MjY1ETQmIyMRKahSUlJSqKYbHR0bOAK8WFX+nlVYZCAkAWwkIP4M
    //8ACgAAAYYCvAAiABgRAAEGAeN1DwAIsQIBsA+wMyv//wApAAABdQNeACIAGAAAAAMB2gDDAAD/
    /wAKAAABhgK8ACIAGBEAAQYB43UPAAixAgGwD7AzK///ACkAAAF1A1EAIgAYAAAAAwHUAMMAAAAB
    ACkAAAFVArwACwApQCYAAgADBAIDZQABAQBdAAAAF0sABAQFXQAFBRgFTBEREREREAYHGisTIRUj
    FTMVIxUzFSEpASy+l5e+/tQCvGS5ZNdkAP//ACkAAAFVA14AIgAdAAAAAwHWAL8AAP//ACkAAAFV
    A14AIgAdAAAAAwHbAL8AAP//ACkAAAFVA14AIgAdAAAAAwHaAL8AAP//ACkAAAFVA14AIgAdAAAA
    AwHZAL8AAP//ACkAAAFVA1EAIgAdAAAAAwHTAL8AAP//ACkAAAFVA1EAIgAdAAAAAwHUAL8AAP//
    ACkAAAFVA14AIgAdAAAAAwHVAL8AAP//ACkAAAFVA0IAIgAdAAAAAwHeAL8AAP//ACn/bQFVArwA
    IgAdAAAAAwHiAQcAAAABACkAAAFMArwACQAjQCAAAgADBAIDZQABAQBdAAAAF0sABAQYBEwRERER
    EAUHGSsTIRUjFTMVIxEjKQEjtY6ObgK8ZMNk/s8AAAD//wApAAABTANRACIAJwAAAAMB1AC3AAAA
    AQAh//YBaQLGAB0AaEuwCVBYQCUAAQIFAgFwAAUABAMFBGUAAgIAXwAAAB1LAAMDBl8HAQYGHgZM
    G0AmAAECBQIBBX4ABQAEAwUEZQACAgBfAAAAHUsAAwMGXwcBBgYeBkxZQA8AAAAdABwREiMiEyUI
    BxorFiY1ETQ2MzIWFRUjNTQjIhURFDMyNTUjNTMVFAYjdVRUUFBUaDk5OTk3n1RQCltVAXBVW1tV
    PENFRf6BRESJZOVVWwAAAP//ACH/9gFpA14AIgApAAAAAwHbAMUAAP//ACH/9gFpA14AIgApAAAA
    AwHZAMUAAP//ACH/QwFpAsYAIgApAAAAAwHgAMQAAP//ACH/9gFpA1EAIgApAAAAAwHUAMUAAAAB
    ACkAAAF7ArwACwAhQB4AAQAEAwEEZQIBAAAXSwUBAwMYA0wRERERERAGBxorEzMRMxEzESMRIxEj
    KW52bm52bgK8/uMBHf1EATv+xQAA//8ACgAAAawCvAAiAC4JAAEHAeQA2wDQAAixAQGw0LAzKwAA
    //8AKQAAAXsDXgAiAC4AAAADAdkA0gAAAAEAKQAAAJcCvAADABNAEAAAABdLAAEBGAFMERACBxYr
    EzMRIylubgK8/UT//wAp//wBowK8ACIAMQAAAAMAPADAAAD//wAkAAAA4gNeACIAMQAAAAIB1mAA
    AAD////qAAAA1gNeACIAMQAAAAIB22AAAAD////aAAAA5gNeACIAMQAAAAIB2WAAAAD////iAAAA
    3gNRACIAMQAAAAIB02AAAAD//wApAAAAlwNRACIAMQAAAAIB1GAAAAD////eAAAAnANeACIAMQAA
    AAIB1WAAAAD////tAAAA0wNCACIAMQAAAAIB3mAAAAD//wAR/20ArQK8ACIAMQAAAAIB4l8AAAD/
    ///VAAAA6wNiACIAMQAAAAIB3WAAAAAAAQAQ//wA4wK8AA0AKUAmAgEAAQEBAgACSgABARdLAAAA
    AmADAQICGAJMAAAADQAMEyMEBxYrFic1FjMyNjURMxEUBiMlFRAUISBuT1EEBGQEISICGf3qVlQA
    AP//ABD//AEfA14AIgA8AAAAAwHWAJ0AAP//ABD//AEjA14AIgA8AAAAAwHZAJ0AAAABACkAAAGT
    ArwACwAgQB0JCAUCBAIAAUoBAQAAF0sDAQICGAJMExISEAQHGCsTMxETMwMTIwMHFSMpboxug4Vz
    XSxuArz+2QEn/v/+RQE4Wd8AAP//ACn/QwGTArwAIgA/AAAAAwHgANkAAAABACkAAAFMArwABQAZ
    QBYAAAAXSwABAQJeAAICGAJMEREQAwcXKxMzETMVISlutf7dArz9qGQA//8AKQAAAUwDXgAiAEEA
    AAACAdZqAAAA//8AKQAAAUwCvAAiAEEAAAADAdgBBAAA//8AKf9DAUwCvAAiAEEAAAADAeAAuwAA
    AAIAKQAAAUwCvAAFAAkAI0AgAAMABAEDBGUAAAAXSwABAQJeAAICGAJMERERERAFBxkrEzMRMxUh
    EzMVIylutf7drWpqArz9qGQBk2oAAAAAAQAKAAABYAK8AA0ALEApDAsKCQYFBAMIAgEBSgABARdL
    AwECAgBeAAAAGABMAAAADQANFREEBxYrJRUhNQc1NxEzETcVBxUBYP7dMzNud3dkZKA3eDcBpP7S
    f3h/sgAAAQApAAAB8QK8AA8AIUAeDAgCAwIAAUoBAQAAF0sEAwICAhgCTBMTERMQBQcZKxMzEzMT
    MxEjESMDIwMjESMpnUYCRp1oAlBcUAJgArz+CwH1/UQCEv3uAhL97v//ACkAAAHxA1EAIgBHAAAA
    AwHUAQ0AAAABACkAAAGCArwACwAeQBsIAgICAAFKAQEAABdLAwECAhgCTBMRExAEBxgrEzMTMxEz
    ESMDIxEjKYprAmJxhAJiArz+XQGj/UQB//4BAAAA//8AKQAAAYIDXgAiAEkAAAADAdYA1gAA//8A
    KQAAAYIDXgAiAEkAAAADAdoA1gAA//8AKf9DAYICvAAiAEkAAAADAeAA1gAAAAEAKf9WAYICvAAY
    ADNAMBELAgECAgEAAQEBBAADSgAABQEEAARkAwECAhdLAAEBGAFMAAAAGAAXExEYIwYHGCsWJzUW
    MzI2NTQmJwMjESMRMxMzETMRFAYj0hUQFxYeBAaBAmKKawJiS0mqBF8EGx4RGhUB3f31Arz+dAGM
    /UJUVAAA//8AKQAAAYIDYgAiAEkAAAADAd0A1gAAAAIAIf/2AW8CxgANABcALEApAAICAF8AAAAd
    SwUBAwMBXwQBAQEeAUwODgAADhcOFhMRAA0ADCUGBxUrFiY1ETQ2MzIWFREUBiM2NRE0IyIVERQz
    d1ZWUVFWVlE5OTk5ClxUAXBUXFxU/pBUXGRFAX5FRf6CRQAA//8AIf/2AW8DXgAiAE8AAAADAdYA
    yAAA//8AIf/2AW8DXgAiAE8AAAADAdsAyAAA//8AIf/2AW8DXgAiAE8AAAADAdkAyAAA//8AIf/2
    AW8DUQAiAE8AAAADAdMAyAAA//8AIf/2AW8DXgAiAE8AAAADAdUAyAAA//8AIf/2AYwDXgAiAE8A
    AAADAdcAxAAA//8AIf/2AW8DQgAiAE8AAAADAd4AyAAA//8AF//mAXkC1gAiAE8AAAADAeYAyAAA
    //8AF//mAXkDXgAiAE8AAAAjAeYAyAAAAAMB1gDIAAD//wAh//YBbwNiACIATwAAAAMB3QDIAAAA
    AgAhAAACKwK8ABEAGwA6QDcAAgADBAIDZQYBAQEAXQAAABdLCQcCBAQFXQgBBQUYBUwSEgAAEhsS
    GhUTABEAEBERERElCgcZKzImNRE0NjMhFSMVMxUjFTMVITcRIyIGFREUFjNzUlJSAWa+l5e+/po6
    OBsdHRtYVQFiVVhkuWTXZGQB9CAk/pQkIAACACkAAAFvArwACwAVACpAJwUBAwABAgMBZwAEBABd
    AAAAF0sAAgIYAkwNDBQSDBUNFRElIAYHFysTMzIWFRUUBiMjESMTMjY1NTQmIyMVKaJSUlJSNG6i
    GxsbGzQCvFhVRVVY/uMBgR4kUyQe1wD//wApAAABbwNRACIAWwAAAAMB1AC/AAAAAgApAAABbwK8
    AA0AFwAuQCsAAQAFBAEFZwYBBAACAwQCZwAAABdLAAMDGANMDw4WFA4XDxcRJSEQBwcYKxMzFTMy
    FhUVFAYjIxUjEzI2NTU0JiMjFSluNFJSUlI0bqIbGxsbNAK8Y1hVRVVYugEeHiRTJB7XAAAAAgAh
    /78BigLGABYAIAA/QDwQAQIFAQEAAgJKAAIGAQMCA2MABAQBXwABAR1LBwEFBQBfAAAAHgBMFxcA
    ABcgFx8cGgAWABUnJSIIBxcrBCcGIyImNRE0NjMyFhURFAcWFjMzFSMmNRE0IyIVERQzASIRHypR
    VlZRUVYfBhIRER1sOTk5QUMMXFQBcFRcXFT+kEYtCgZkm0UBfkVF/oJFAAIAKQAAAXwCvAAaACQA
    MkAvBwECBAFKBgEEAAIBBAJnAAUFAF0AAAAXSwMBAQEYAUwcGyMhGyQcJBEmHSAHBxgrEzMyFhUV
    FAcVFhYVFRQWFyMmJjU1NCYjIxEjEzI2NTU0JiMjFSmjVU5IKCEECHAGBB8mJm6WISEbHTICvE9S
    K20dAgxKPnseJRIRHieAMCb+1AGQIig2JiLI//8AKQAAAXwDXgAiAF8AAAADAdYAwQAA//8AKQAA
    AXwDXgAiAF8AAAADAdoAwQAA//8AKf9DAXwCvAAiAF8AAAADAeAAywAAAAEAFv/2AV4CxgAnAJFL
    sAtQWEAjAAMEAAQDcAAAAQEAbgAEBAJfAAICHUsAAQEFYAYBBQUeBUwbS7AMUFhAJAADBAAEA3AA
    AAEEAAF8AAQEAl8AAgIdSwABAQVgBgEFBR4FTBtAJQADBAAEAwB+AAABBAABfAAEBAJfAAICHUsA
    AQEFYAYBBQUeBUxZWUAOAAAAJwAmIxMqIhMHBxkrFiY1NTMVFDMyNjU0JicmJjU0NjMyFhUVIzU0
    JiMiFRQWFxYWFRQGI2hSaDkcHSg2RDZUUE9RaBwbNyk2RTRVUQpbVSgwRCElLEMvPGE9U1tbVR0k
    JCFDJkIvPGJCVlwAAP//ABb/9gFeA14AIgBjAAAAAwHWALoAAP//ABb/9gFeA14AIgBjAAAAAwHa
    ALoAAP//ABb/bQFeAsYAIgBjAAAAAwHhALoAAP//ABb/9gFeA14AIgBjAAAAAwHZALoAAP//ABb/
    QwFeAsYAIgBjAAAAAwHgALoAAP//ABb/9gFeA1EAIgBjAAAAAwHUALoAAAABACkAAAGBArwAGQA1
    QDICAQQAFQMCAwQCSgADBAIEAwJ+AAQEAF0AAAAXSwACAgFfBQEBARgBTBESJSEnEAYHGisTIRUH
    FhUVFAYjIzUzMjY1NTQmIyM1NyMRIykBTk1XUlIbGxsbGxsbSXRuArxivRuGT1VYZB4kXSQeXbb9
    qAAAAAABAAwAAAFgArwABwAbQBgCAQAAAV0AAQEXSwADAxgDTBERERAEBxgrEyM1IRUjESN/cwFU
    c24CWGRk/agAAAAAAQAMAAABYAK8AA8AL0AsBAEAAwEBAgABZQgHAgUFBl0ABgYXSwACAhgCTAAA
    AA8ADxEREREREREJBxsrExUzFSMRIxEjNTM1IzUhFe1MTG5MTHMBVAJYuWT+xQE7ZLlkZAAA//8A
    DAAAAWADXgAiAGsAAAADAdoAtgAA//8ADP9tAWACvAAiAGsAAAADAeEAtgAA//8ADP9DAWACvAAi
    AGsAAAADAeAAtgAA//8ADAAAAWADUQAiAGsAAAADAdQAtgAAAAEAJf/2AW0CvAARACFAHgIBAAAX
    SwABAQNgBAEDAx4DTAAAABEAEBMjEwUHFysWJjURMxEUFjMyNjURMxEUBiN5VG4dGxsdalRQCltV
    Ahb94iQgICQCHv3qVVv//wAl//YBbQNeACIAcQAAAAMB1gDJAAD//wAl//YBbQNeACIAcQAAAAMB
    2wDJAAD//wAl//YBbQNeACIAcQAAAAMB2QDJAAD//wAl//YBbQNRACIAcQAAAAMB0wDJAAD//wAl
    //YBbQNeACIAcQAAAAMB1QDJAAD//wAl//YBjQNeACIAcQAAAAMB1wDFAAD//wAl//YBbQNCACIA
    cQAAAAMB3gDJAAD//wAl/20BbQK8ACIAcQAAAAMB4gDbAAD//wAl//YBbQOQACIAcQAAAAMB3ADJ
    AAD//wAl//YBbQNiACIAcQAAAAMB3QDJAAAAAQAMAAABcgK8AAcAG0AYAgECAAFKAQEAABdLAAIC
    GAJMERMQAwcXKxMzEzMTMwMjDG9IAkhlapICvP3hAh/9RAAAAAABAA8AAAIeArwADwAhQB4MBgID
    AwABSgIBAgAAF0sEAQMDGANMExETExAFBxkrEzMTMxMzEzMTMwMjAyMDIw9qMQI0eDQCMV9HiTIC
    MpICvP3mAhr95gIa/UQB2P4oAP//AA8AAAIeA14AIgB9AAAAAwHWARcAAP//AA8AAAIeA14AIgB9
    AAAAAwHZARcAAP//AA8AAAIeA1EAIgB9AAAAAwHTARcAAP//AA8AAAIeA14AIgB9AAAAAwHVARcA
    AAABAAsAAAGLArwADQAfQBwKBwMDAgABSgEBAAAXSwMBAgIYAkwTEhMRBAcYKxMDMxczNzMDEyMn
    Iwcjinl0SgJMaHl/dFACUmgBZgFW4uL+qv6a9PQAAAAAAQAJAAABgQK8AAkAHUAaBwMAAwIAAUoB
    AQAAF0sAAgIYAkwSExEDBxcrEwMzEzMTMwMRI46FdUsCS2uFbgEqAZL+/wEB/m7+1gAA//8ACQAA
    AYEDXgAiAIMAAAADAdYAxQAA//8ACQAAAYEDXgAiAIMAAAADAdkAxQAA//8ACQAAAYEDUQAiAIMA
    AAADAdMAxQAA//8ACQAAAYEDXgAiAIMAAAADAdUAxQAAAAEAEwAAAVUCvAAJAClAJgUBAAEAAQMC
    AkoAAAABXQABARdLAAICA10AAwMYA0wREhERBAcYKzcTIzUhFQMzFSETzMIBOMzM/r5iAfZkYv4K
    ZAAA//8AEwAAAVUDXgAiAIgAAAADAdYAuQAA//8AEwAAAVUDXgAiAIgAAAADAdoAuQAA//8AEwAA
    AVUDUQAiAIgAAAADAdQAuQAA//8ADAAAAYUCvAACAAQAAP//AAwAAAGFA14AIgAEAAAAAwHWAMkA
    AP//AAwAAAGFA14AIgAEAAAAAwHbAMkAAP//AAwAAAGFA14AIgAEAAAAAwHZAMkAAP//AAwAAAGF
    A1EAIgAEAAAAAwHTAMkAAP//AAwAAAGFA14AIgAEAAAAAwHVAMkAAP//AAwAAAGFA0IAIgAEAAAA
    AwHeAMkAAP//AAz/bQGFArwAIgAEAAAAAwHiATcAAP//AAwAAAGFA5AAIgAEAAAAAwHcAMkAAP//
    AAwAAAGFA2IAIgAEAAAAAwHdAMkAAP//AAoAAAIuArwAAgAOAAD//wAKAAACLgNeACIADgAAAAMB
    1gEgAAD//wApAAABfQK8AAIAEAAA//8AKQAAAX0DUQAiABAAAAADAdQAvwAA//8AIv/2AWYCxgAC
    ABIAAP//ACL/9gFmA14AIgASAAAAAwHWAMEAAP//ACL/9gFmA14AIgASAAAAAwHaAMEAAP//ACL/
    bQFmAsYAIgASAAAAAwHhAMUAAP//ACL/9gFmA14AIgASAAAAAwHZAMEAAP//ACL/9gFmA1EAIgAS
    AAAAAwHUAMEAAP//ACkAAAF1ArwAAgAYAAD//wAKAAABhgK8ACIAGBEAAQYB43UPAAixAgGwD7Az
    K///ACkAAAF1A14AIgAYAAAAAwHaAMMAAP//AAoAAAGGArwAIgAYEQABBgHjdQ8ACLECAbAPsDMr
    //8AKQAAAXUDUQAiABgAAAADAdQAwwAA//8AKQAAAVUCvAACAB0AAP//ACkAAAFVA14AIgAdAAAA
    AwHWAL8AAP//ACkAAAFVA14AIgAdAAAAAwHbAL8AAP//ACkAAAFVA14AIgAdAAAAAwHaAL8AAP//
    ACkAAAFVA14AIgAdAAAAAwHZAL8AAP//ACkAAAFVA1EAIgAdAAAAAwHTAL8AAP//ACkAAAFVA1EA
    IgAdAAAAAwHUAL8AAP//ACkAAAFVA14AIgAdAAAAAwHVAL8AAP//ACkAAAFVA0IAIgAdAAAAAwHe
    AL8AAP//ACn/bQFVArwAIgAdAAAAAwHiAQcAAP//ACkAAAFMArwAAgAnAAD//wApAAABTANRACIA
    JwAAAAMB1AC3AAD//wAh//YBaQLGAAIAKQAA//8AIf/2AWkDXgAiACkAAAADAdsAxQAA//8AIf/2
    AWkDXgAiACkAAAADAdkAxQAA//8AIf9DAWkCxgAiACkAAAADAeAAxAAA//8AIf/2AWkDUQAiACkA
    AAADAdQAxQAA//8AKQAAAXsCvAACAC4AAP//AAoAAAGsArwAIgAuCQABBwHkANsA0AAIsQEBsNCw
    MysAAP//ACkAAAF7A14AIgAuAAAAAwHZANIAAP//ACkAAACXArwAAgAxAAD//wApAAAAlwK8AAIA
    MQAA//8AJAAAAOIDXgAiADEAAAACAdZgAAAA////6gAAANYDXgAiADEAAAACAdtgAAAA////2gAA
    AOYDXgAiADEAAAACAdlgAAAA////4gAAAN4DUQAiADEAAAACAdNgAAAA//8AKQAAAJcDUQAiADEA
    AAACAdRgAAAA////3gAAAJwDXgAiADEAAAACAdVgAAAA//8AKf/8AaMCvAAiADEAAAADADwAwAAA
    ////7QAAANMDQgAiADEAAAACAd5gAAAA//8AEf9tAK0CvAAiADEAAAACAeJfAAAA////1QAAAOsD
    YgAiADEAAAACAd1gAAAA//8AEP/8AOMCvAACADwAAP//ABD//ADjArwAAgA8AAD//wAQ//wBHwNe
    ACIAPAAAAAMB1gCdAAD//wAQ//wBIwNeACIAPAAAAAMB2QCdAAD//wApAAABkwK8AAIAPwAA//8A
    Kf9DAZMCvAAiAD8AAAADAeAA2QAA//8AKQAAAZMCvAACAD8AAP//ACkAAAFMArwAAgBBAAD//wAp
    AAABTANeACIAQQAAAAIB1moAAAD//wApAAABTAK8ACIAQQAAAAMB2AEEAAD//wAp/0MBTAK8ACIA
    QQAAAAMB4AC7AAD//wApAAABTAK8AAIARQAA//8ACgAAAWACvAACAEYAAP//ACkAAAHxArwAAgBH
    AAD//wApAAAB8QNRACIARwAAAAMB1AENAAD//wApAAABggK8AAIASQAA//8AKQAAAYIDXgAiAEkA
    AAADAdYA1gAA//8ABAAAAfUCvAAiAec5AAACAElzAAAA//8AKQAAAYIDXgAiAEkAAAADAdoA1gAA
    //8AKf9DAYICvAAiAEkAAAADAeAA1gAA//8AKf9WAYICvAACAE0AAP//ACkAAAGCA2IAIgBJAAAA
    AwHdANYAAP//ACH/9gFvAsYAAgBPAAD//wAh//YBbwNeACIATwAAAAMB1gDIAAD//wAh//YBbwNe
    ACIATwAAAAMB2wDIAAD//wAh//YBbwNeACIATwAAAAMB2QDIAAD//wAh//YBbwNRACIATwAAAAMB
    0wDIAAD//wAh//YBbwNeACIATwAAAAMB1QDIAAD//wAh//YBjANeACIATwAAAAMB1wDEAAD//wAh
    //YBbwNCACIATwAAAAMB3gDIAAD//wAX/+YBeQLWACIATwAAAAMB5gDIAAD//wAX/+YBeQNeACIA
    TwAAACMB5gDIAAAAAwHWAMgAAP//ACH/9gFvA2IAIgBPAAAAAwHdAMgAAP//ACEAAAIrArwAAgBa
    AAD//wApAAABbwK8AAIAWwAA//8AKQAAAW8DUQAiAFsAAAADAdQAvwAA//8AKQAAAW8CvAACAF0A
    AP//ACH/vwGKAsYAAgBeAAD//wApAAABfAK8AAIAXwAA//8AKQAAAXwDXgAiAF8AAAADAdYAwQAA
    //8AKQAAAXwDXgAiAF8AAAADAdoAwQAA//8AKf9DAXwCvAAiAF8AAAADAeAAywAA//8AFv/2AV4C
    xgACAGMAAP//ABb/9gFeA14AIgBjAAAAAwHWALoAAP//ABb/9gFeA14AIgBjAAAAAwHaALoAAP//
    ABb/bQFeAsYAIgBjAAAAAwHhALoAAP//ABb/9gFeA14AIgBjAAAAAwHZALoAAP//ABb/QwFeAsYA
    IgBjAAAAAwHgALoAAP//ABb/9gFeA1EAIgBjAAAAAwHUALoAAP//ACkAAAGBArwAAgBqAAD//wAM
    AAABYAK8AAIAawAA//8ADAAAAWACvAACAGwAAP//AAwAAAFgA14AIgBrAAAAAwHaALYAAP//AAz/
    bQFgArwAIgBrAAAAAwHhALYAAP//AAz/QwFgArwAIgBrAAAAAwHgALYAAP//AAwAAAFgA1EAIgBr
    AAAAAwHUALYAAP//ACX/9gFtArwAAgBxAAD//wAl//YBbQNeACIAcQAAAAMB1gDJAAD//wAl//YB
    bQNeACIAcQAAAAMB2wDJAAD//wAl//YBbQNeACIAcQAAAAMB2QDJAAD//wAl//YBbQNRACIAcQAA
    AAMB0wDJAAD//wAl//YBbQNeACIAcQAAAAMB1QDJAAD//wAl//YBjQNeACIAcQAAAAMB1wDFAAD/
    /wAl//YBbQNCACIAcQAAAAMB3gDJAAD//wAl/20BbQK8ACIAcQAAAAMB4gDbAAD//wAl//YBbQOQ
    ACIAcQAAAAMB3ADJAAD//wAl//YBbQNiACIAcQAAAAMB3QDJAAD//wAMAAABcgK8AAIAfAAA//8A
    DwAAAh4CvAACAH0AAP//AA8AAAIeA14AIgB9AAAAAwHWARcAAP//AA8AAAIeA14AIgB9AAAAAwHZ
    ARcAAP//AA8AAAIeA1EAIgB9AAAAAwHTARcAAP//AA8AAAIeA14AIgB9AAAAAwHVARcAAP//AAsA
    AAGLArwAAgCCAAD//wAJAAABgQK8AAIAgwAA//8ACQAAAYEDXgAiAIMAAAADAdYAxQAA//8ACQAA
    AYEDXgAiAIMAAAADAdkAxQAA//8ACQAAAYEDUQAiAIMAAAADAdMAxQAA//8ACQAAAYEDXgAiAIMA
    AAADAdUAxQAA//8AEwAAAVUCvAACAIgAAP//ABMAAAFVA14AIgCIAAAAAwHWALkAAP//ABMAAAFV
    A14AIgCIAAAAAwHaALkAAP//ABMAAAFVA1EAIgCIAAAAAwHUALkAAAADAB4A1gDyAsYAGgAjACcA
    0EAKHAEHBhcBBAcCSkuwFlBYQC4AAQMCAgFwAAAABgcABmcACAAJCAlhAAICA2AAAwNASwsBBwcE
    XwoFAgQEPgRMG0uwLlBYQC8AAQMCAwECfgAAAAYHAAZnAAgACQgJYQACAgNgAAMDQEsLAQcHBF8K
    BQIEBD4ETBtANgABAwIDAQJ+AAQHBQcEBX4AAAAGBwAGZwAIAAkICWEAAgIDYAADA0BLCwEHBwVf
    CgEFBT4FTFlZQBobGwAAJyYlJBsjGyIeHQAaABkTIhMiFQwJGSsSJjU1NDY3NTQjIgYVFSM1NDMy
    FhURIycjBiM2NzUGBhUVFDMHMxUjRSdESh4SEEJlMTI7AwIYLjkHJSMhZ9TUAU0yLgQ9OwM1JRQX
    DQlvOjX++zA1QCRHAh0dCSZzRAAAAAADACMA1gD3AsYADQAZAB0AN0A0AAQABQQFYQACAgBfAAAA
    QEsHAQMDAV8GAQEBPgFMDg4AAB0cGxoOGQ4YExEADQAMJQgJFSsSJjU1NDYzMhYVFRQGIzY1NTQj
    IgYVFRQWMwczFSNaNzczMzc3MyQkEhISEmrU1AFNOjWbNTo6NZs1OkAroysUF6MXFHNEAAACAAwA
    AAGFArwAAwAHACtAKAUBAgABSgAAAgCDAwECAQECVQMBAgIBXQABAgFNBAQEBwQHERAEChYrEzMT
    ITcDIwN+lXL+h/xDAkMCvP1EZAHU/iwAAAAAAQAiAAABcALGACMALUAqIRUCAAFJAAEABAABBGcC
    AQADAwBVAgEAAANdBQEDAANNFiYRJicQBgoaKzczNSYmNTU0NjMyFhUVFAYHFTMVIzU2NjU1NCMi
    FRUUFhcVIyJQKyVWUVFWJStQlxgROTkRGJdkAjBqUsRUXFxUxFJrLwJkZCpUQfpFRfpBVCpkAAAA
    AQAp/2ABcwH0ABIAibUMAQMBAUpLsApQWEAjAgEAAQCDAAMBBAEDBH4ABQQFhAABAwQBVwABAQRf
    AAQBBE8bS7ALUFhAHAIBAAEAgwAFAwWEAAEDAwFXAAEBA18EAQMBA08bQCMCAQABAIMAAwEEAQME
    fgAFBAWEAAEDBAFXAAEBBF8ABAEET1lZQAkRIxETIhAGChorEzMRFDMyNjURMxEjNQYGIyMVIylu
    NBsfbmQPMh8YbgH0/qE5ISQBU/4MNBoenAAAAAABAA4AAAG2AfQACwAkQCEFAQMAA4QAAQAAAVUA
    AQEAXQQCAgABAE0RERERERAGChorEyM1IRUjESMRIxEjSjwBqDxuVG4BkGRk/nABkP5wAAIAIf/2
    AW8CxgANABcALEApAAICAF8AAAAdSwUBAwMBXwQBAQEeAUwODgAADhcOFhMRAA0ADCUGBxUrFiY1
    ETQ2MzIWFREUBiM2NRE0IyIVERQzd1ZWUVFWVlE5OTk5ClxUAXBUXFxU/pBUXGRFAX5FRf6CRQAA
    AAEAUAAAATECvAAJAB1AGgABAAADAQBlAAICF0sAAwMYA0wRExEQBAcYKxMjNTI2NjczESPDcy85
    Ig1KbgIWThAlI/1EAAAAAAEAJwAAAW8CxgAeAE5LsAlQWEAcAAEAAwABcAAAAAJfAAICHUsAAwME
    XQAEBBgETBtAHQABAAMAAQN+AAAAAl8AAgIdSwADAwRdAAQEGARMWbcRGSMSKAUHGSs3NDY3NjY1
    NCYjIhUVIzU0NjMyFhUUBgcGBhUVMxUhJzA+PS8dHDloVFBQVD1LMSLR/sJMS2tBQVwyLSNFS0RV
    W1tVQHpPNEElD2QAAAEAIf/2AWkCxgAvALW1JwECAwFKS7AJUFhALAAFBAMEBXAAAAIBAQBwAAMA
    AgADAmcABAQGXwAGBh1LAAEBB2AIAQcHHgdMG0uwC1BYQC0ABQQDBAVwAAACAQIAAX4AAwACAAMC
    ZwAEBAZfAAYGHUsAAQEHYAgBBwceB0wbQC4ABQQDBAUDfgAAAgECAAF+AAMAAgADAmcABAQGXwAG
    Bh1LAAEBB2AIAQcHHgdMWVlAEAAAAC8ALiMSJSElIhMJBxsrFiY1NTMVFDMyNjU1NCYjIzUzMjY1
    NTQmIyIVFSM1NDYzMhYVFRQGBxUWFhUVFAYjdFNoORwdIiYlKCEhHhk1aFNOT1ImKCsmU1EKWlQ5
    PkUjLDkwKWQiKDMkIkEuJVRaWVQZOUUPAhBIOD5UWQACAA8AAAGDArwACgAOADJALwwBAgEBSgIB
    AgFJBgUCAgMBAAQCAGYAAQEXSwAEBBgETAsLCw4LDhERERIQBwcZKzcjNRMzETMVIxUjNREjA+HS
    yHg0NG4CbH9kAdn+J2R/4wER/u8AAAEAJv/2AW4CvAAfAH61FQECBgFKS7AJUFhALAADAgACAwB+
    AAABAQBuAAYAAgMGAmcABQUEXQAEBBdLAAEBB2AIAQcHHgdMG0AtAAMCAAIDAH4AAAECAAF8AAYA
    AgMGAmcABQUEXQAEBBdLAAEBB2AIAQcHHgdMWUAQAAAAHwAeIxERISMiEwkHGysWJjU1MxUUMzI1
    NTQjIhUVIxMhFSMHMzYzMhYVFRQGI3pUaDk5OTloFAEiwAkCH0A8PlRQCltVNz9ERJ1FRQYBh2Sn
    M1JOnlVbAAAAAAIAJP/2AXICxgAbACUAd7URAQUDAUpLsA1QWEAmAAECAwIBcAADAAUGAwVnAAIC
    AF8AAAAdSwgBBgYEXwcBBAQeBEwbQCcAAQIDAgEDfgADAAUGAwVnAAICAF8AAAAdSwgBBgYEXwcB
    BAQeBExZQBUcHAAAHCUcJCEfABsAGiUiEyQJBxgrFiY1ETQzMhYVFSM1NCMiBhUVMzYzMhYVFRQG
    IzY1NTQjIhUVFDN6VqhQVGg5Hx4CHUc8PlZROTk5OQpcVAFqtltVDRRFJjCGPVJOfVRcZER8RUV8
    RAABACIAAAFsArwABgAfQBwEAQABAUoAAAABXQABARdLAAICGAJMEhEQAwcXKwEjNSEVAyMBAN4B
    SqxwAlhkYP2kAAAAAAMAHP/2AXQCxgAcACYAMABEQEEUBgIEAwFKBwEDAAQFAwRnAAICAF8AAAAd
    SwgBBQUBXwYBAQEeAUwnJx0dAAAnMCcvLCodJh0lIiAAHAAbLQkHFSsWJjU1NDY3NSYmNTU0NjMy
    FhUVFAcVFhYVFRQGIxI1NTQjIhUVFDMSNTU0IyIVFRQzdVkiJiMhV1FRV0QmIllTOjo6Oj4+Pj4K
    WVQ+NEcUAhNDNB1UWVlUHWQmAhRHND5UWQGpRjdGRjdG/rtPQ09PQ08AAgAe//YBbALGABsAJQB3
    tQsBAgYBSkuwDVBYQCYAAAIBAQBwCAEGAAIABgJnAAUFA18AAwMdSwABAQRgBwEEBB4ETBtAJwAA
    AgECAAF+CAEGAAIABgJnAAUFA18AAwMdSwABAQRgBwEEBB4ETFlAFRwcAAAcJRwkIR8AGwAaJSUi
    EwkHGCsWJjU1MxUUMzI2NTUjBiMiJjU1NDYzMhYVERQjEjU1NCMiFRUUM3RUaDkfHgIdRzw+VlFR
    Vqg6OTk5CltVDRRFJjCGPVJOfVRcXFT+lrYBZ0V8RER8RQAAAP//ACH/9gFvAsYAAgEeAAD//wAS
    AAAA8wK8AAIBH8IA//8AGAAAAWACxgACASDxAP//ABT/9gFcAsYAAgEh8wD//wAOAAABggK8AAIB
    Iv8A//8AHP/2AWQCvAACASP2AP//ACH/9gFvAsYAAgEk/QD//wAMAAABVgK8AAIBJeoA//8AGv/2
    AXICxgACASb+AP//ABr/9gFoAsYAAgEn/AD//wAh//YBbwLGAAIBHgAA//8AEgAAAPMCvAACAR/C
    AP//ABgAAAFgAsYAAgEg8QD//wAU//YBXALGAAIBIfMA//8ADgAAAYICvAACASL/AP//ABz/9gFk
    ArwAAgEj9gD//wAh//YBbwLGAAIBJP0A//8ADAAAAVYCvAACASXqAP//ABr/9gFyAsYAAgEm/gD/
    /wAa//YBaALGAAIBJ/wAAAIAI/+1APcBhQANABcALEApAAICAF8AAAAtSwUBAwMBXwQBAQEuAUwO
    DgAADhcOFhMRAA0ADCUGCBUrFiY1NTQ2MzIWFRUUBiM2NTU0IyIVFRQzWTY2NDQ2NjQkJCQkSzo2
    8DY6OjbwNjo/LPosLPosAAAAAQA6/78AygF7AAgAHUAaAAEAAAMBAGUAAgInSwADAygDTBESERAE
    CBgrEyM1MjY3MxEjhEorKQ4uRgESMRgg/kQAAAABACb/vwD2AYUAHgBOS7APUFhAHAABAAMAAXAA
    AAACXwACAi1LAAMDBF0ABAQoBEwbQB0AAQADAAEDfgAAAAJfAAICLUsAAwMEXQAEBCgETFm3ERkj
    EigFCBkrFzQ2NzY2NTQmIyIVFSM1NDYzMhYVFAYHBgYVFTMVIyYeJyceERMkQjUzMzUmMB8WhcoP
    MEUqKDwjGBcsKSU2OTg0K00zIikZDD8AAAABACL/tQDyAYUALQC1tSYBAgMBSkuwD1BYQCwABQQD
    BAVwAAACAQEAcAADAAIAAwJnAAQEBl8ABgYtSwABAQdgCAEHBy4HTBtLsBJQWEAtAAUEAwQFcAAA
    AgECAAF+AAMAAgADAmcABAQGXwAGBi1LAAEBB2AIAQcHLgdMG0AuAAUEAwQFA34AAAIBAgABfgAD
    AAIAAwJnAAQEBl8ABgYtSwABAQdgCAEHBy4HTFlZQBAAAAAtACwjEiQhJSITCQgbKxYmNTUzFRQz
    MjY1NTQmIyM1MzI1NTQmIyIVFSM1NDYzMhYVFRQGBxUWFRUUBiNXNUIkEhIVGBgbKhISJEI1MzM1
    GBkxNTNLOjYlKiwXHCgfGT8wHRwXLBsWNjo6NhMjKwsCFUglNjoAAAACABf/vwEDAXsACgAOAFdA
    CwwBAgEBSgIBAgFJS7AhUFhAGAABASdLBgUCAgIAXgMBAAArSwAEBCgETBtAFgYFAgIDAQAEAgBm
    AAEBJ0sABAQoBExZQA4LCwsOCw4RERESEAcIGSs3IzUTMxEzFSMVIzc1IwechX9MISFGAQJFDz8B
    Lf7TP1CPr68AAAEAJv+1APYBewAfAH61FQECBgFKS7ASUFhALAADAgACAwB+AAABAQBuAAYAAgMG
    AmcABQUEXQAEBCdLAAEBB2AIAQcHLgdMG0AtAAMCAAIDAH4AAAECAAF8AAYAAgMGAmcABQUEXQAE
    BCdLAAEBB2AIAQcHLgdMWUAQAAAAHwAeIxEREiMiEwkIGysWJjU1MxUUMzI1NTQjIhUVIzczFSMH
    MzYzMhYVFRQGI1s1QiQkJCRCDbh7BQITKSYnNTNLOjYZHSsrZCwsCf8/bCE1MWY2OgAAAgAl/7UA
    +QGFABsAJQBBQD4KCAICAREBBAICSgACAAQFAgRnAAEBAF8AAAAtSwcBBQUDXwYBAwMuA0wcHAAA
    HCUcJCEfABsAGiUmJAgIFysWJjU1NDMyFhUVIzU0IyIGFRUzNjMyFhUVFAYjNjU1NCMiFRUUM1w3
    azM1QiQUEwISLSYnNzMkJCQkSzo27XM6NgYLLBgfXCY0MU82Oj8rTywsTysAAAAAAQAj/78A9QF7
    AAYAH0AcBAEAAQFKAAAAAV0AAQEnSwACAigCTBIREAMIFysTIzUzFQMjsY7Sb0YBPD89/oEAAAMA
    IP+1APoBhQAZACMALQBEQEESBQIEAwFKBwEDAAQFAwRnAAICAF8AAAAtSwgBBQUBXwYBAQEuAUwk
    JBoaAAAkLSQsKScaIxoiHx0AGQAYKwkIFSsWJjU1NDc1JjU1NDYzMhYVFRQHFRYVFRQGIxI1NTQj
    IhUVFDMWNTU0IyIVFRQzWTkrKzk0NDkrKzk0JycnJycnJydLOzUjRBgCGEAXNTs7NRdAGAIYRCM1
    OwERLyIvLyIv0jIvMjIvMgAAAAIAIf+1APUBhQAbACUAQUA+CwEBBQQCAgABAkoHAQUAAQAFAWcA
    BAQCXwACAi1LAAAAA18GAQMDLgNMHBwAABwlHCQhHwAbABolJSYICBcrFiY1NTMVFDMyNjU1IwYj
    IiY1NTQ2MzIWFRUUIzY1NTQjIhUVFDNXNUIkFBMCEi0mJzczMzdrJSQkJEs6NgYLLBgfXCY0MU82
    Ojo27XPrLE8rK08sAAAAAAIAI//2APcBxgANABcAKkAnAAAAAgMAAmcFAQMDAV8EAQEBHgFMDg4A
    AA4XDhYTEQANAAwlBgcVKxYmNTU0NjMyFhUVFAYjNjU1NCMiFRUUM1k2NjQ0NjY0JCQkJAo6NvA2
    Ojo28DY6Pyz6LCz6LAABADoAAADKAbwACAAdQBoAAQAAAwEAZQACAgNdAAMDGANMERIREAQHGCsT
    IzUyNjczESOESispDi5GAVMxGCD+RAAAAAEAJgAAAPYBxgAeAEpLsA9QWEAaAAEAAwABcAACAAAB
    AgBnAAMDBF0ABAQYBEwbQBsAAQADAAEDfgACAAABAgBnAAMDBF0ABAQYBExZtxEZIxIoBQcZKzc0
    Njc2NjU0JiMiFRUjNTQ2MzIWFRQGBwYGFRUzFSMmHicnHhETJEI1MzM1JjAfFoXKMjBFKig8IxgX
    LCklNjk4NCtNMyIpGQw/AAAAAQAi//YA8gHGAC0Ar7UmAQIDAUpLsA9QWEAqAAUEAwQFcAAAAgEB
    AHAABgAEBQYEZwADAAIAAwJnAAEBB2AIAQcHHgdMG0uwElBYQCsABQQDBAVwAAACAQIAAX4ABgAE
    BQYEZwADAAIAAwJnAAEBB2AIAQcHHgdMG0AsAAUEAwQFA34AAAIBAgABfgAGAAQFBgRnAAMAAgAD
    AmcAAQEHYAgBBwceB0xZWUAQAAAALQAsIxIkISUiEwkHGysWJjU1MxUUMzI2NTU0JiMjNTMyNTU0
    JiMiFRUjNTQ2MzIWFRUUBgcVFhUVFAYjVzVCJBISFRgYGyoSEiRCNTMzNRgZMTUzCjo2JSosFxwo
    Hxk/MB0cFywbFjY6OjYTIysLAhVIJTY6AAIAFwAAAQMBvAAKAA4AMkAvDAECAQFKAgECAUkAAQIB
    gwYFAgIDAQAEAgBmAAQEGARMCwsLDgsOEREREhAHBxkrNyM1EzMRMxUjFSM3NSMHnIV/TCEhRgEC
    RVA/AS3+0z9Qj6+vAAAAAQAm//YA9gG8AB8AerUVAQIGAUpLsBJQWEAqAAMCAAIDAH4AAAEBAG4A
    BAAFBgQFZQAGAAIDBgJnAAEBB2AIAQcHHgdMG0ArAAMCAAIDAH4AAAECAAF8AAQABQYEBWUABgAC
    AwYCZwABAQdgCAEHBx4HTFlAEAAAAB8AHiMRERIjIhMJBxsrFiY1NTMVFDMyNTU0IyIVFSM3MxUj
    BzM2MzIWFRUUBiNbNUIkJCQkQg24ewUCEykmJzUzCjo2GR0rK2QsLAn/P2whNTFmNjoAAAIAJf/2
    APkBxgAbACUAP0A8CggCAgERAQQCAkoAAAABAgABZwACAAQFAgRnBwEFBQNfBgEDAx4DTBwcAAAc
    JRwkIR8AGwAaJSYkCAcXKxYmNTU0MzIWFRUjNTQjIgYVFTM2MzIWFRUUBiM2NTU0IyIVFRQzXDdr
    MzVCJBQTAhItJic3MyQkJCQKOjbtczo2BgssGB9cJjQxTzY6PytPLCxPKwAAAQAjAAAA9QG8AAYA
    HUAaBAEAAQFKAAEAAAIBAGUAAgIYAkwSERADBxcrEyM1MxUDI7GO0m9GAX0/Pf6BAAAAAAMAIP/2
    APoBxgAZACMALQBCQD8SBQIEAwFKAAAAAgMAAmcHAQMABAUDBGcIAQUFAV8GAQEBHgFMJCQaGgAA
    JC0kLCknGiMaIh8dABkAGCsJBxUrFiY1NTQ3NSY1NTQ2MzIWFRUUBxUWFRUUBiMSNTU0IyIVFRQz
    FjU1NCMiFRUUM1k5Kys5NDQ5Kys5NCcnJycnJycnCjs1I0QYAhhAFzU7OzUXQBgCGEQjNTsBES8i
    Ly8iL9IyLzIyLzIAAgAh//YA9QHGABsAJQA/QDwLAQEFBAICAAECSgACAAQFAgRnBwEFAAEABQFn
    AAAAA18GAQMDHgNMHBwAABwlHCQhHwAbABolJSYIBxcrFiY1NTMVFDMyNjU1IwYjIiY1NTQ2MzIW
    FRUUIzY1NTQjIhUVFDNXNUIkFBMCEi0mJzczMzdrJSQkJAo6NgYLLBgfXCY0MU82Ojo27XPrLE8r
    K08sAAACACMA9gD3AsYADQAXAClAJgUBAwQBAQMBYwACAgBfAAAAHQJMDg4AAA4XDhYTEQANAAwl
    BgcVKzYmNTU0NjMyFhUVFAYjNjU1NCMiFRUUM1k2NjQ0NjY0JCQkJPY6NvA2Ojo28DY6Pyz6LCz6
    LAAAAQA6AQAAygK8AAgAHUAaAAEAAAMBAGUAAwMCXQACAhcDTBESERAEBxgrEyM1MjY3MxEjhEor
    KQ4uRgJTMRgg/kQAAAABACYBAAD2AsYAHgBIS7APUFhAGQABAAMAAXAAAwAEAwRhAAAAAl8AAgId
    AEwbQBoAAQADAAEDfgADAAQDBGEAAAACXwACAh0ATFm3ERkjEigFBxkrEzQ2NzY2NTQmIyIVFSM1
    NDYzMhYVFAYHBgYVFTMVIyYeJyceERMkQjUzMzUmMB8WhcoBMjBFKig8IxgXLCklNjk4NCtNMyIp
    GQw/AAAAAAEAIgD2APICxgAtAKy1JgECAwFKS7APUFhAKQAFBAMEBXAAAAIBAQBwAAMAAgADAmcA
    AQgBBwEHZAAEBAZfAAYGHQRMG0uwElBYQCoABQQDBAVwAAACAQIAAX4AAwACAAMCZwABCAEHAQdk
    AAQEBl8ABgYdBEwbQCsABQQDBAUDfgAAAgECAAF+AAMAAgADAmcAAQgBBwEHZAAEBAZfAAYGHQRM
    WVlAEAAAAC0ALCMSJCElIhMJBxsrNiY1NTMVFDMyNjU1NCYjIzUzMjU1NCYjIhUVIzU0NjMyFhUV
    FAYHFRYVFRQGI1c1QiQSEhUYGBsqEhIkQjUzMzUYGTE1M/Y6NiUqLBccKB8ZPzAdHBcsGxY2Ojo2
    EyMrCwIVSCU2OgAAAAACABcBAAEDArwACgAOADJALwwBAgEBSgIBAgFJAAQABIQGBQICAwEABAIA
    ZgABARcBTAsLCw4LDhERERIQBwcZKxMjNRMzETMVIxUjNzUjB5yFf0whIUYBAkUBUD8BLf7TP1CP
    r68AAAEAJgD2APYCvAAfAHi1FQECBgFKS7ASUFhAKQADAgACAwB+AAABAQBuAAYAAgMGAmcAAQgB
    BwEHZAAFBQRdAAQEFwVMG0AqAAMCAAIDAH4AAAECAAF8AAYAAgMGAmcAAQgBBwEHZAAFBQRdAAQE
    FwVMWUAQAAAAHwAeIxEREiMiEwkHGys2JjU1MxUUMzI1NTQjIhUVIzczFSMHMzYzMhYVFRQGI1s1
    QiQkJCRCDbh7BQITKSYnNTP2OjYZHSsrZCwsCf8/bCE1MWY2OgAAAAACACUA9gD5AsYAGwAlAD5A
    OwoIAgIBEQEEAgJKAAIABAUCBGcHAQUGAQMFA2MAAQEAXwAAAB0BTBwcAAAcJRwkIR8AGwAaJSYk
    CAcXKzYmNTU0MzIWFRUjNTQjIgYVFTM2MzIWFRUUBiM2NTU0IyIVFRQzXDdrMzVCJBQTAhItJic3
    MyQkJCT2Ojbtczo2BgssGB9cJjQxTzY6PytPLCxPKwAAAAEAIwEAAPUCvAAGAB9AHAQBAAEBSgAC
    AAKEAAAAAV0AAQEXAEwSERADBxcrEyM1MxUDI7GO0m9GAn0/Pf6BAAADACAA9gD6AsYAGQAjAC0A
    QUA+EgUCBAMBSgcBAwAEBQMEZwgBBQYBAQUBYwACAgBfAAAAHQJMJCQaGgAAJC0kLCknGiMaIh8d
    ABkAGCsJBxUrNiY1NTQ3NSY1NTQ2MzIWFRUUBxUWFRUUBiMSNTU0IyIVFRQzFjU1NCMiFRUUM1k5
    Kys5NDQ5Kys5NCcnJycnJycn9js1I0QYAhhAFzU7OzUXQBgCGEQjNTsBES8iLy8iL9IyLzIyLzIA
    AAIAIQD2APUCxgAbACUAPkA7CwEBBQQCAgABAkoHAQUAAQAFAWcAAAYBAwADYwAEBAJfAAICHQRM
    HBwAABwlHCQhHwAbABolJSYIBxcrNiY1NTMVFDMyNjU1IwYjIiY1NTQ2MzIWFRUUIzY1NTQjIhUV
    FDNXNUIkFBMCEi0mJzczMzdrJSQkJPY6NgYLLBgfXCY0MU82Ojo27XPrLE8rK08sAAAAAgAjAVUA
    9wMlAA0AFwAqQCcAAAACAwACZwUBAwMBXwQBAQE+AUwODgAADhcOFhMRAA0ADCUGCRUrEiY1NTQ2
    MzIWFRUUBiM2NTU0IyIVFRQzWTY2NDQ2NjQkJCQkAVU6NvA2Ojo28DY6Pyz6LCz6LAAAAAABADoB
    XwDKAxsACAAdQBoAAQAAAwEAZQACAgNdAAMDOANMERIREAQJGCsTIzUyNjczESOESispDi5GArIx
    GCD+RAAAAAEAJgFfAPYDJQAeAEpLsA9QWEAaAAEAAwABcAACAAABAgBnAAMDBF0ABAQ4BEwbQBsA
    AQADAAEDfgACAAABAgBnAAMDBF0ABAQ4BExZtxEZIxIoBQkZKxM0Njc2NjU0JiMiFRUjNTQ2MzIW
    FRQGBwYGFRUzFSMmHicnHhETJEI1MzM1JjAfFoXKAZEwRSooPCMYFywpJTY5ODQrTTMiKRkMPwAA
    AQAiAVUA8gMlAC0Ar7UmAQIDAUpLsA9QWEAqAAUEAwQFcAAAAgEBAHAABgAEBQYEZwADAAIAAwJn
    AAEBB2AIAQcHPgdMG0uwElBYQCsABQQDBAVwAAACAQIAAX4ABgAEBQYEZwADAAIAAwJnAAEBB2AI
    AQcHPgdMG0AsAAUEAwQFA34AAAIBAgABfgAGAAQFBgRnAAMAAgADAmcAAQEHYAgBBwc+B0xZWUAQ
    AAAALQAsIxIkISUiEwkJGysSJjU1MxUUMzI2NTU0JiMjNTMyNTU0JiMiFRUjNTQ2MzIWFRUUBgcV
    FhUVFAYjVzVCJBISFRgYGyoSEiRCNTMzNRgZMTUzAVU6NiUqLBccKB8ZPzAdHBcsGxY2Ojo2EyMr
    CwIVSCU2OgAAAAACABcBXwEDAxsACgAOADJALwwBAgEBSgIBAgFJAAECAYMGBQICAwEABAIAZgAE
    BDgETAsLCw4LDhERERIQBwkZKxMjNRMzETMVIxUjNzUjB5yFf0whIUYBAkUBrz8BLf7TP1CPr68A
    AAEAJgFVAPYDGwAfAHq1FQECBgFKS7ASUFhAKgADAgACAwB+AAABAQBuAAQABQYEBWUABgACAwYC
    ZwABAQdgCAEHBz4HTBtAKwADAgACAwB+AAABAgABfAAEAAUGBAVlAAYAAgMGAmcAAQEHYAgBBwc+
    B0xZQBAAAAAfAB4jERESIyITCQkbKxImNTUzFRQzMjU1NCMiFRUjNzMVIwczNjMyFhUVFAYjWzVC
    JCQkJEINuHsFAhMpJic1MwFVOjYZHSsrZCwsCf8/bCE1MWY2OgACACUBVQD5AyUAGwAlAD9APAoI
    AgIBEQEEAgJKAAAAAQIAAWcAAgAEBQIEZwcBBQUDXwYBAwM+A0wcHAAAHCUcJCEfABsAGiUmJAgJ
    FysSJjU1NDMyFhUVIzU0IyIGFRUzNjMyFhUVFAYjNjU1NCMiFRUUM1w3azM1QiQUEwISLSYnNzMk
    JCQkAVU6Nu1zOjYGCywYH1wmNDFPNjo/K08sLE8rAAEAIwFfAPUDGwAGAB1AGgQBAAEBSgABAAAC
    AQBlAAICOAJMEhEQAwkXKxMjNTMVAyOxjtJvRgLcPz3+gQAAAAADACABVQD6AyUAGQAjAC0AQkA/
    EgUCBAMBSgAAAAIDAAJnBwEDAAQFAwRnCAEFBQFfBgEBAT4BTCQkGhoAACQtJCwpJxojGiIfHQAZ
    ABgrCQkVKxImNTU0NzUmNTU0NjMyFhUVFAcVFhUVFAYjEjU1NCMiFRUUMxY1NTQjIhUVFDNZOSsr
    OTQ0OSsrOTQnJycnJycnJwFVOzUjRBgCGEAXNTs7NRdAGAIYRCM1OwERLyIvLyIv0jIvMjIvMgAA
    AAACACEBVQD1AyUAGwAlAD9APAsBAQUEAgIAAQJKAAIABAUCBGcHAQUAAQAFAWcAAAADXwYBAwM+
    A0wcHAAAHCUcJCEfABsAGiUlJggJFysSJjU1MxUUMzI2NTUjBiMiJjU1NDYzMhYVFRQjNjU1NCMi
    FRUUM1c1QiQUEwISLSYnNzMzN2slJCQkAVU6NgYLLBgfXCY0MU82Ojo27XPrLE8rK08sAAH/ggAA
    ANcCvAADABNAEAAAABdLAAEBGAFMERACBxYrEzMBI5FG/vFGArz9RAAA//8AOgAAAmkCvAAiAVEA
    AAAjAWQBGgAAAAMBSAFzAAD//wA6//YCZQK8ACIBUQAAACMBZAEaAAAAAwFJAXMAAP//ACb/9gJl
    AsYAIgFSAAAAIwFkARoAAAADAUkBcwAA//8AOgAAAnYCvAAiAVEAAAAjAWQBGgAAAAMBSgFzAAD/
    /wAiAAACdgLGACIBUwAAACMBZAEaAAAAAwFKAXMAAP//ADr/9gJtArwAIgFRAAAAIwFkARoAAAAD
    AU4BcwAA//8AIv/2Am0CxgAiAVMAAAAjAWQBGgAAAAMBTgFzAAD//wAm//YCbQK8ACIBVQAAACMB
    ZAEaAAAAAwFOAXMAAP//ACP/9gJtArwAIgFXAAAAIwFkARoAAAADAU4BcwAAAAEADwFHAZcCvAAO
    ABxAGQ4NDAsKCQgHBAMCAQwARwAAABcATBUBBxUrEzcnNxcnMwc3FwcXBycHPmqZHI8UWhSPHJlq
    SE1NAXxwIVVEnp5EVSFwNYeHAAABAAkAAAF8ArwAAwATQBAAAAAXSwABARgBTBEQAgcWKxMzASMJ
    XwEUXwK8/UQAAAABACkBKQCTAZMAAwAYQBUAAAEBAFUAAAABXQABAAFNERACBxYrEzMVIylqagGT
    agABACMA6wEJAdEACwAeQBsAAAEBAFcAAAABXwIBAQABTwAAAAsACiQDBxUrNiY1NDYzMhYVFAYj
    ZkNDMDBDQzDrQzAwQ0MwMEMAAAAAAgApAAAAkwHnAAMABwAdQBoAAAABAgABZQACAgNdAAMDGANM
    EREREAQHGCsTMxUjETMVIylqampqAedq/u1qAAEAKf+IAJMAagAGADu1BAEAAQFKS7ALUFhAEQAC
    AAACbwABAQBdAAAAGABMG0AQAAIAAoQAAQEAXQAAABgATFm1EhEQAwcXKzMjNTMVByNNJGo3M2pf
    gwADAB8AAAHVAGoAAwAHAAsAG0AYBAICAAABXQUDAgEBGAFMEREREREQBgcaKzczFSM3MxUjNzMV
    Ix9qaqZqaqZqampqampqagACADIAAACgArwABQAJAB9AHAABAQBdAAAAF0sAAgIDXQADAxgDTBER
    EhEEBxgrExEzEQcjBzMVIzJuDlIMamoBmAEk/tzfT2oAAAAAAgAyAAAAoAK8AAMACQAfQBwAAQEA
    XQAAABdLAAICA10AAwMYA0wSEhEQBAcYKxMzFSMDNzMXESM0amoCDlIObgK8av7S39/+3AAAAAIA
    EAAAAYwCvAAbAB8AR0BEBwUCAw4IAgIBAwJmEA8JAwEMCgIACwEAZQYBBAQXSw0BCwsYC0wcHBwf
    HB8eHRsaGRgXFhUUExIRERERERERERARBx0rNyM3MzcjNzM3MwczNzMHMwcjBzMHIwcjNyMHIxM3
    IwdBMQgxEzIIMhFXEUcRVxEzCDMTMwgzFVcVRxVXuxNHE8hOt06hoaGhTrdOyMjIARa3twAAAAAB
    ACkAAACTAGoAAwATQBAAAAABXQABARgBTBEQAgcWKzczFSMpampqagAAAAIAEwAAAVcCxgAdACEA
    XkuwCVBYQCMAAQADAAFwAAMEAAMEfAAAAAJfAAICHUsABAQFXQAFBRgFTBtAJAABAAMAAQN+AAME
    AAMEfAAAAAJfAAICHUsABAQFXQAFBRgFTFlACRERGSMTKAYHGis3NDY3NjY1NCYjIgYVFSM1NDYz
    MhYVFAYHBgYVFSMHMxUjdRcfJBocGxscaFJPUFMhKCAZYAVqauMlQywzSikkISEkTEVVW1tVLlU1
    KzkbJk9qAAIAFP/2AVgCvAADACEAXkuwCVBYQCMABQADAAUDfgADAgIDbgAAAAFdAAEBF0sAAgIE
    YAAEBB4ETBtAJAAFAAMABQN+AAMCAAMCfAAAAAFdAAEBF0sAAgIEYAAEBB4ETFlACRkjEykREAYH
    GisTIzUzBxQGBwYGFRQWMzI2NTUzFRQGIyImNTQ2NzY2NTUz+2pqBRcfJBocGxscaFJPUFMhKCAZ
    YAJSauMlQywzSikkISEkTEVVW1tVLlU1KzkbJgAAAAACACYB2gEqArwAAwAHABdAFAMBAQEAXQIB
    AAAXAUwREREQBAcYKxMzByM3MwcjJnAbO3pwGzsCvOLi4gABACYB2gCWArwAAwATQBAAAQEAXQAA
    ABcBTBEQAgcWKxMzByMmcBs7ArziAAIAI/+IAJMB5wADAAoATbUIAQIDAUpLsAtQWEAZAAQCAgRv
    AAAAAQMAAWUAAwMCXQACAhgCTBtAGAAEAgSEAAAAAQMAAWUAAwMCXQACAhgCTFm3EhERERAFBxkr
    EzMVIxMjNTMVByMpamokJGo9MwHnav6Dal+DAAEACQAAAXwCvAADABNAEAAAABdLAAEBGAFMERAC
    BxYrATMBIwEdX/7sXwK8/UQAAAEAAP+mASz/9gADACCxBmREQBUAAAEBAFUAAAABXQABAAFNERAC
    BxYrsQYARBUhFSEBLP7UClAAAQAV/84A+wLuACEAOEA1FwEAAQFKAAIAAwECA2cAAQAABAEAZwAE
    BQUEVwAEBAVfBgEFBAVPAAAAIQAgKyElERUHBxkrFiY1NTQmIzUyNjU1NDYzMxUjIgYVFRQHFRYV
    FRQWMzMVI5I+GiUlGj4xOBAbGj09GhsQODI4N7gjGVoZI7g3OFofKJZGEgISRpYoH1oAAAEAGf/O
    AP8C7gAhADJALwcBBAMBSgACAAEDAgFnAAMABAADBGcAAAUFAFcAAAAFXwAFAAVPJREVISsgBgca
    KzczMjY1NTQ3NSY1NTQmIyM1MzIWFRUUFjMVIgYVFRQGIyMZEBsaPT0aGxA4MT4aJSUaPjE4KB8o
    lkYSAhJGligfWjg3uCMZWhkjuDc4AAAAAAEAO//OAPEC7gAHACJAHwAAAAECAAFlAAIDAwJVAAIC
    A10AAwIDTRERERAEBxgrEzMVIxEzFSM7tkhItgLuWv2UWgAAAQAj/84A2QLuAAcAIkAfAAIAAQAC
    AWUAAAMDAFUAAAADXQADAANNEREREAQHGCs3MxEjNTMRIyNISLa2KAJsWvzgAAABADX/zgDxAu4A
    EwAoQCUAAAABAgABZwACAwMCVwACAgNfBAEDAgNPAAAAEwASJSElBQcXKxYmNRE0NjMzFSMiBhUR
    FBYzMxUjfEdHUyIbGxgYGxsiMkZTAe5TRlobJP4SJBtaAAAAAAEAI//OAN8C7gATACJAHwACAAEA
    AgFnAAADAwBXAAAAA18AAwADTyUhJSAEBxgrNzMyNjURNCYjIzUzMhYVERQGIyMjGxsYGBsbIlNH
    R1MiKBskAe4kG1pGU/4SU0YAAAEAAAExAfQBiwADABhAFQAAAQEAVQAAAAFdAAEAAU0REAIHFisR
    IRUhAfT+DAGLWgAAAAABAAABMQEsAYsAAwAYQBUAAAEBAFUAAAABXQABAAFNERACBxYrESEVIQEs
    /tQBi1oAAAAAAQAAATEBkAGLAAMAGEAVAAABAQBVAAAAAV0AAQABTREQAgcWKxEhFSEBkP5wAYta
    AAAAAAEAGQEsAPUBkAADABhAFQAAAQEAVQAAAAFdAAEAAU0REAIHFisTMxUjGdzcAZBk//8AGQEs
    APUBkAACAYkAAAACAA4A5gE/AcgABQALACRAIQkDAgEAAUoCAQABAQBVAgEAAAFdAwEBAAFNEhIS
    EQQHGCsTNzMHFyM3NzMHFyMOTVA5OVBITFA4OFABWm5udHRubnQAAAAAAgARAOYBQQHIAAUACwAz
    QDAKBwQBBAEAAUoCAQABAQBVAgEAAAFdBQMEAwEAAU0GBgAABgsGCwkIAAUABRIGBxUrNzcnMxcH
    MzcnMxcHETg4UExMRDg4UExM5nRubnR0bm50AAEADgDmAKsByAAFAB5AGwMBAQABSgAAAQEAVQAA
    AAFdAAEAAU0SEQIHFisTNzMHFyMOTVA5OVABWm5udAAAAAABABEA5gCuAcgABQAlQCIEAQIBAAFK
    AAABAQBVAAAAAV0CAQEAAU0AAAAFAAUSAwcVKzc3JzMXBxE5OVBNTeZ0bm50AAIAI/+IAScAagAG
    AA0ARrYLBAIAAQFKS7ALUFhAFAUBAgAAAm8EAQEBAF0DAQAAGABMG0ATBQECAAKEBAEBAQBdAwEA
    ABgATFlACRIRERIREAYHGiszIzUzFQcjNyM1MxUHI00kaj0zviRqPTNqX4N4al+DAAAAAAIAKQHa
    AS0CvAAGAA0AI0AgBwACAgEBSgQBAQUBAgECYgMBAAAXAEwRERIREREGBxorEzczBzMVIzc3Mwcz
    FSMpPTMqJGqUPTMqJGoCOYN4al+DeGoAAAACACMB2gEnArwABgANAEa2CwQCAAEBSkuwC1BYQBQF
    AQIAAAJvAwEAAAFdBAEBARcATBtAEwUBAgAChAMBAAABXQQBAQEXAExZQAkSERESERAGBxorEyM1
    MxUHIzcjNTMVByNNJGo9M74kaj0zAlJqX4N4al+DAAABACkB2gCZArwABgAcQBkAAQIBAUoAAQAC
    AQJiAAAAFwBMERERAwcXKxM3MwczFSMpPTMqJGoCOYN4agABACMB2gCTArwABgA7tQQBAAEBSkuw
    C1BYQBEAAgAAAm8AAAABXQABARcATBtAEAACAAKEAAAAAV0AAQEXAExZtRIREAMHFysTIzUzFQcj
    TSRqPTMCUmpfgwAA//8AKv+IAJQAagACAXMBAAABACr/7AFuAsYAIQCiQAwdGgIABBMQAgMBAkpL
    sBlQWEAlBgEFAAIABQJ+AAIBAAIBfAAAAARdAAQEF0sAAQEDXQADAxgDTBtLsDFQWEAiBgEFAAIA
    BQJ+AAIBAAIBfAABAAMBA2EAAAAEXQAEBBcATBtAKAYBBQACAAUCfgACAQACAXwABAAABQQAZwAB
    AwMBVwABAQNdAAMBA01ZWUAOAAAAIQAhGRUSIyIHBxkrATU0IyIVERQzMjU1MxUUBgcVIzUmJjU1
    NDY3NTMVFhYVFQEGNzc3N2g8Olo5Ozs5Wjo8AbwnQUH+9UBAQTlFVwxMTQxWRfxFVgxDQgxXRSAA
    AgAfALUBcQIHABsAJwBGQEMPDgwIBgUGAgAaFhQTAQUBAwJKDQcCAEgbFQIBRwAAAAIDAAJnBAED
    AQEDVwQBAwMBXwABAwFPHBwcJxwmJywpBQcXKzc3JjU0Nyc3FzYzMhc3FwcWFRQHFwcnBiMiJwc2
    NjU0JiMiBhUUFjMfOhISOjE1HiUlHjUxOhISOjE1HiUlHjWQHR0YGB0dGOY1HSYnHDUxOxMTOzE1
    HCcmHTUxOxMTO3QdGBgdHRgYHQAAAQAk/8kBbALpACsAP0A8FhMCBAIpAAIFAQJKAAMEAAQDAH4A
    AAEEAAF8AAIABAMCBGcAAQUFAVcAAQEFXQAFAQVNGyIVGyIUBgcaKzcmJjU1MxUUMzI1NCYnJiY1
    NDY3NTMVFhYVFSM1NCMiFRQWFxYWFRQGBxUjmzo9aDk5KDZDNjs5Wjo8aDc3KDZDNj06Wg8MVkMu
    NT0/Jz8qNVw6QVQNPT0MVUMUGz48JD0rNl08RFcMRgAAAAEAF//2AXUCxgAvANxLsAlQWEA4AAUG
    AwYFcAAMAAsLDHAHAQMIAQIBAwJlCQEBCgEADAEAZQAGBgRfAAQEHUsACwsNYA4BDQ0eDUwbS7AM
    UFhAOQAFBgMGBXAADAALAAwLfgcBAwgBAgEDAmUJAQEKAQAMAQBlAAYGBF8ABAQdSwALCw1gDgEN
    DR4NTBtAOgAFBgMGBQN+AAwACwAMC34HAQMIAQIBAwJlCQEBCgEADAEAZQAGBgRfAAQEHUsACwsN
    YA4BDQ0eDUxZWUAaAAAALwAuKyonJSIhIB8REyMTIxERERMPBx0rFiY1NSM1MzUjNTM1NDYzMhYV
    FSM1NCYjIgYVFTMVIxUzFSMVFBYzMjY1NTMVFAYjhFEcHBwcUVBQUWgbGxsbmpqamhsbGxtoUVAK
    W1VyNzc3WVVbW1UhKCUgICVgNzc3eiQgICRCOlVbAAADABP/yQF7AukAIgAsADYAYkBfDgECAxQB
    DQocAQABA0oGAQQDBwRVBQEDCwECCgMCaA4BCgANAQoNZw8MAgEIAQAHAQBlBgEEBAddCQEHBAdN
    Li0kIzUzLTYuNispIywkLCIhIB8eHRERERERERAQBxsrNyM1MxEjNTM1MxUzNTMVFhUVFAYHFRYW
    FRUUBgcVIzUjFSMTMjY1NTQmIyMVEzI2NTU0JiMjFVlGKChGPjo+YSIlKyc3NT46PmchIRsdISsd
    HCEmHRlkAcJkRkZGThp6DzZFEQIRSzkWQVAOV1BQAcwiKBgmIqr+6B8mGjAltAAAAQAcAAABegK8
    ABsAPkA7AAEIAUkACQgJhAAEBQEDAgQDZQYBAgcBAQACAWUAAAgIAFUAAAAIXwAIAAhPGxoTERIR
    ESIREiEKCh0rEzUzMjY1IzUzNCYjIzUhFSMWFzMVIw4CIxMjHFwrKbCwKStcAVhUEwY7OwQvRCLa
    hQE5VR4kVSQeVVUcJlUuRST+xwAAAQAjAAABcQLGACgAbrUAAQgHAUpLsAtQWEAmAAMEAQQDcAUB
    AQYBAAcBAGUABAQCXwACAh1LAAcHCF0ACAgYCEwbQCcAAwQBBAMBfgUBAQYBAAcBAGUABAQCXwAC
    Ah1LAAcHCF0ACAgYCExZQAwRExEWIxMmERUJBx0rNzY2NTQnIzUzLgI1NDYzMhYVFSM1NCYjIgYV
    FBYXFzMVIxQGBzMVISMtMgNcShkXEFROUFJoHBsbHBYTD3pnHCnJ/rleFU4tEQ9VLjA+KEdYW1Up
    MCQhISQnRiojVTRSJGQAAAABAAsAAAGFArwAFwA5QDYKAQMEAUoGAQMHAQIBAwJmCAEBCQEACgEA
    ZQUBBAQXSwAKChgKTBcWFRQRERETERERERALBx0rNyM1MzUjNTMDMxMzEzMDMxUjFTMVIxUjkVlZ
    WVJ/dUwCTGt/Vl1dXW5wRUlFAXn++wEF/odFSUVwAAEALgEeAK4BngADABhAFQAAAQEAVQAAAAFd
    AAEAAU0REAIKFisTMxUjLoCAAZ6AAAEAEQAAAX8CvAADABFADgAAAQCDAAEBdBEQAgoWKwEzASMB
    K1T+5lQCvP1EAAAAAAEAGwCuAXUCDAALACZAIwACAQUCVQMBAQQBAAUBAGUAAgIFXQAFAgVNERER
    EREQBgcaKxMjNTM1MxUzFSMVI6GGhk6Ghk4BN06Hh06JAAAAAQAbATcBdQGFAAMAGEAVAAABAQBV
    AAAAAV0AAQABTREQAgoWKxMhFSEbAVr+pgGFTgAAAAEAKAC7AWcCAQALAAazCQUBMCs3Nyc3FzcX
    BxcHJwcoamk1amo1amo1amvwbm01bW41bm41bm4AAwAbAJABdQIrAAMABwALACxAKQAAAAECAAFl
    AAIAAwQCA2UABAUFBFUABAQFXQAFBAVNEREREREQBgcaKxMzFSMHIRUhFzMVI5NqangBWv6meGpq
    AitqPE49agACACUA5gFrAdYAAwAHACJAHwAAAAECAAFlAAIDAwJVAAICA10AAwIDTRERERAEBxgr
    EyEVIRUhFSElAUb+ugFG/roB1k5UTgABACUAjAFrAjAAEwBsS7AOUFhAKQAEAwMEbgAJAAAJbwUB
    AwYBAgEDAmYHAQEAAAFVBwEBAQBdCAEAAQBNG0AnAAQDBIMACQAJhAUBAwYBAgEDAmYHAQEAAAFV
    BwEBAQBdCAEAAQBNWUAOExIRERERERERERAKCh0rNyM1MzcjNTM3MwczFSMHMxUjByNaNWMylcM1
    TjU1YzKVwzVO5k5UTlpaTlROWgABADYAtQFoAgcABgAGswYDATArEzcnNQUVBTbT0wEy/s4BBVlZ
    UIRKhAAAAAEAKAC1AVoCBwAGAAazBgIBMCsTNSUVBxcVKAEy09MBOUqEUFlZUAACADMAmgFlAhsA
    BgAKACJAHwYFBAMCAQAHAEgAAAEBAFUAAAABXQABAAFNERcCChYrEzcnNQUVBRUhFSEzxsYBMv7O
    ATL+zgFLQEBQa0prE04AAAACACsAmgFdAhsABgAKACJAHwYFBAMCAQAHAEgAAAEBAFUAAAABXQAB
    AAFNERcCChYrAQcXFSU1JQEhFSEBXcbG/s4BMv7OATL+zgHLQEBQa0pr/s1OAAAAAQAkAKQBagIg
    AA8AL0AsAAMCA4MEAQIFAQEAAgFlBgEABwcAVQYBAAAHXgAHAAdOERERERERERAIBxwrNzM1IzUz
    NTMVMxUjFTMVISR8fHxOfHx8/rrybk5yck5uTgAAAgAMAL8BhAH9ABkAMwBNQEoNAQEAJhkCBAIn
    AQUEA0oMAQBIMwEGRwAAAAMCAANnAAEAAgQBAmcABQcGBVcABAAHBgQHZwAFBQZfAAYFBk8kJSQl
    JCUkIggKHCsTNjYzMhYXFhYzMjY3FwYGIyImJyYmIyIGBwc2NjMyFhcWFjMyNjcXBgYjIiYnJiYj
    IgYHDB81JREeGxsVCxEYGDkfNSURHhsbFQsRGBg5HzUlER4bGxULERgYOR81JREeGxsVCxEYGAGW
    NS8MERELGSMrNS8MERELGSOBNS8MERELGSMrNS8MERELGSMAAAABAAwBFQGEAacAGQA4sQZkREAt
    DQEBAAFKDAEASBkBAkcAAQMCAVcAAAADAgADZwABAQJfAAIBAk8kJSQiBAcYK7EGAEQTNjYzMhYX
    FhYzMjY3FwYGIyImJyYmIyIGBwwfNSURHhsbFQsRGBg5HzUlER4bGxULERgYAUA1LwwREQsZIys1
    LwwREQsZIwAAAAABABYArgFwAYUABQA+S7AJUFhAFgACAAACbwABAAABVQABAQBdAAABAE0bQBUA
    AgAChAABAAABVQABAQBdAAABAE1ZtREREAMHFysBITUhFSMBIv70AVpOATdO1wAAAAADABoAtQJp
    AgcAGQAnADYASkBHMh0VCAQFBAFKAQEABgEEBQAEZwoHCQMFAgIFVwoHCQMFBQJfCAMCAgUCTygo
    GhoAACg2KDUuLBonGiYiIAAZABgkJSQLChcrNiY1NDYzMhYXMzY2MzIWFRQGIyImJyMGBiM2Njc3
    JyYmIyIGFRQWMwQ2NTQmIyIGBgcHFxYWM2ZMTEkvQh0EG0UxS0xMSS9CHQUaRTEmJRAKDRMjHCAo
    JyEBNSgnIRYfEg4MDxUiG7VjR0dhLS8rMWNHR2EtLysxUSYiFRQgITMmJjMCMyYmNBUbGRUWHyAA
    AAMANgAWAqgCnAAVAB4AJwBEQEELCQICACUkHgwBBQMCFAEBAwNKCgEASBUBAUcAAAACAwACZwQB
    AwEBA1cEAQMDAV8AAQMBTx8fHycfJiQpJgUKFys3NyY1NDY2MzIXNxcHFhUUBgYjIicHASYjIgYG
    FRQXFjY2NTQnARYzNj09UY9ZalI5RD09UY9ZalI5AWw0QztfNh3uXzYd/tY0Q1RAU3JblFQ8PD5A
    U3JblFQ8PAICJjtpQUU0bDtpQUU0/sgmAAABADb/VgFYAu4AFQA3QDQMAQIBDQICAAIBAQMAA0oA
    AQACAAECZwAAAwMAVwAAAANfBAEDAANPAAAAFQAUIyQjBQoXKxYnNRYzMjURNDYzMhcVJiMiFREU
    BiNQGhYXLUZAKBoSGy1GQKoKZAsyAnVFSQpjCjL9i0VJAAD//wAiAAABcALGAAIBGwAA//8ADAAA
    AYUCvAACARoAAAABADH/YAGgArwABwAgQB0DAQECAYQAAAICAFUAAAACXQACAAJNEREREAQKGCsT
    IREjESMRIzEBb26TbgK8/KQC+P0IAAEAGf9gAYMCvAALADFALgIBAQAHAQICAQABAwIDSgAAAAEC
    AAFlAAIDAwJVAAICA10AAwIDTRESERMEChgrFxMDNSEVIxMDMxUhGbm5AWr0sbH0/pY+AU0BS2Jk
    /rb+tmQAAAABABD/vwHMArwACAAqQCcEAQMAAUoAAgECgwADAAOEAAEAAAFVAAEBAF0AAAEATRES
    ERAEChgrEyM1MxMTMwMjU0OXQZBUt28BN07+zQJq/QMAAP//ACn/YAFzAfQAAgEcAAAAAgAh//YB
    iALGAB8AKwCMQBIKAQACCAEFACIhHAMCBQYFA0pLsA9QWEAqAAIBAAECcAADAAECAwFnAAAABQYA
    BWcIAQYEBAZXCAEGBgRfBwEEBgRPG0ArAAIBAAECAH4AAwABAgMBZwAAAAUGAAVnCAEGBAQGVwgB
    BgYEXwcBBAYET1lAFSAgAAAgKyAqJiQAHwAeIxImJQkKGCsWNTc3NjYzMhczNzc0JiMiBwcnNzY2
    MzIWFRQHAwYGIzY3NyYmIyIPAhQzIQEJBUA6TBgCCgEcHDcEAWYBCFJOSlQBGQZVTDUFCQUbGTUE
    CAE4CqIXekxPQIIUJyFDEgMLVVZPQB0Q/pdTWGZBjxkaQ3EbNAAFACP/9gIqAsYADQARABsAKQAz
    AMBLsBFQWEAlBgsCBQgKAgEJBQFoAAQEAF8CAQAAHUsNAQkJA18MBwIDAxgDTBtLsBhQWEArAAYA
    CAEGCGgLAQUKAQEJBQFnAAQEAF8CAQAAHUsNAQkJA18MBwIDAxgDTBtAMwAGAAgBBghoCwEFCgEB
    CQUBZwACAhdLAAQEAF8AAAAdSwADAxhLDQEJCQdfDAEHBx4HTFlZQCYqKhwcEhIAACozKjIvLRwp
    HCgjIRIbEhoXFREQDw4ADQAMJQ4HFSsSJjU1NDYzMhYVFRQGIxMzASMSNTU0IyIVFRQzACY1NTQ2
    MzIWFRUUBiM2NTU0IyIVFRQzWTY2NDQ2NjT+Rv7xRjUkJCQA/zY2NDQ2NjQkJCQkATc6Nq82Ojo2
    rzY6AYX9RAF2LLksLLks/oA6Nq82Ojo2rzY6Pyy5LCy5LAAABwAj//YDKgLGAA0AEQAbACkANwBB
    AEsA4kuwEVBYQCsIBg8DBQwKDgMBCwUBaAAEBABfAgEAAB1LEw0SAwsLA18RCRAHBAMDGANMG0uw
    GFBYQDEIAQYMAQoBBgpoDwEFDgEBCwUBZwAEBABfAgEAAB1LEw0SAwsLA18RCRAHBAMDGANMG0A5
    CAEGDAEKAQYKaA8BBQ4BAQsFAWcAAgIXSwAEBABfAAAAHUsAAwMYSxMNEgMLCwdfEQkQAwcHHgdM
    WVlANkJCODgqKhwcEhIAAEJLQkpHRThBOEA9Oyo3KjYxLxwpHCgjIRIbEhoXFREQDw4ADQAMJRQH
    FSsSJjU1NDYzMhYVFRQGIxMzASMSNTU0IyIVFRQzACY1NTQ2MzIWFRUUBiMyJjU1NDYzMhYVFRQG
    IyY1NTQjIhUVFDMgNTU0IyIVFRQzWTY2NDQ2NjT+Rv7xRjUkJCQA/zY2NDQ2NjTMNjY0NDY2NNwk
    JCQBJCQkJAE3OjavNjo6Nq82OgGF/UQBdiy5LCy5LP6AOjavNjo6Nq82Ojo2rzY6OjavNjo/LLks
    LLksLLksLLksAAAAAgAU//YBfALGAAUACQAaQBcJCAcDBAEAAUoAAAEAgwABAXQSEQIKFisTEzMT
    AyMTJwcXFKMio6Mia1paWgFeAWj+mP6YAWjY2NgAAAIAFwAsAmMCYgATAB4AOkA3AAEAAYMCAQAF
    AQMGAANnCAEGBAQGVwgBBgYEXwcBBAYETxQUAAAUHhQdGRcAEwASERERJgkKGCs2JiY1NDY2MzM1
    MxUzFSMVFAYGIzY2NTUjIgYVFBYzuGg5Om1KO5yEhDpnQyAoPCgqKB8sOWZCQmY5dHSYPElsOZor
    KD0oICAoAAACABn/xAKgAuQANwBGARJLsB1QWEAUHQEJA0I7IQMFCQ8BAQUzAQcBBEobS7AnUFhA
    FB0BCQNCOyEDCgkPAQEFMwEHAQRKG0AUHQEJA0I7IQMKCQ8BAgUzAQcBBEpZWUuwHVBYQC0AAAAG
    AwAGZwQBAwAJBQMJZwwKAgUCAQEHBQFoAAcICAdXAAcHCF8LAQgHCE8bS7AnUFhAMgAAAAYDAAZn
    BAEDAAkKAwlnDAEKBQEKVwAFAgEBBwUBaAAHCAgHVwAHBwhfCwEIBwhPG0AzAAAABgMABmcEAQMA
    CQoDCWcMAQoAAgEKAmcABQABBwUBaAAHCAgHVwAHBwhfCwEIBwhPWVlAGTg4AAA4RjhFPz0ANwA2
    JCQjEyYkJSUNBxwrFiY1NDY2MzIWFRQGBiMiJyMGBiMiJjU0Nzc2MzIXMzczAwcUMzI2NTQmIyIG
    FRQWMzI2NwcGBiMSPwI0JiMiBg8CFBYzt55Tp3eUgj5ZLFEGAg8uIS0xAgsRZz4UAgldHQEUJyli
    ZYSLdXQ8YTIIL2I8LQcKARgUGRwECQEXFTy7o3/Md6CGcIw9Qh8dPzkMFmWUPTn+6RATiVNiccSu
    fIkeJmAfGQEkP18MFhYdIlUPGhkAAAAAAgAi//YBjQK8ACoANQDAQA4GAQUCLAEJBSYBBgkDSkuw
    EVBYQCkAAwECAgNwBAECCAEFCQIFaAABAQBdAAAAF0sLAQkJBl8KBwIGBhgGTBtLsBhQWEAqAAMB
    AgEDAn4EAQIIAQUJAgVoAAEBAF0AAAAXSwsBCQkGXwoHAgYGGAZMG0AuAAMBAgEDAn4EAQIIAQUJ
    AgVoAAEBAF0AAAAXSwAGBhhLCwEJCQdfCgEHBx4HTFlZQBgrKwAAKzUrNC8tACoAKRQRERElIS0M
    BxsrFiY1NTQ2NzUmJjU1NDYzMxUjIgYVFRQWMzM1MxUzFSMVFBYXIyYnIwYGIzY3NSMiBhUVFBYz
    YD4mKyclUlJ+fBsdISErbB8fBAhuCAICEi8jXQkqJiIcGQpSTkk3ShECEEc4DVVYZCAkKygiTk5k
    5h4lEhYhISBkP6IpMEcjHgAAAQAa/58BjgK8AA8AI0AgAAADAgMAAn4EAQICggADAwFdAAEBFwNM
    ERERJhAFBxkrEyImJjU1NDYzMxEjESMRI64qQydkVLxSPFIBMSxOMTNSW/zjAs39MwAAAAACABf/
    lQF5AsYANwBDAJZACUM9MBQEAAMBSkuwDVBYQCAAAwQABANwAAABAQBuAAEGAQUBBWQABAQCXwAC
    Ah0ETBtLsA9QWEAhAAMEAAQDcAAAAQQAAXwAAQYBBQEFZAAEBAJfAAICHQRMG0AiAAMEAAQDAH4A
    AAEEAAF8AAEGAQUBBWQABAQCXwACAh0ETFlZQBEAAAA3ADYlIyAfHBojEwcHFisWJjU1MxUUFjMy
    NjU0JicmJjU0Njc1JiY1NDYzMhYVFSM1NCYjIgYVFBYXFhYVFAYHFRYWFRQGIxI2NTQmJwYGFRQW
    F3dVaB8dHR8lMVRBJCclHVdRUVVoHx0dHyUxVEEkJyYcV1EqHiooIB4qKGtPQCgZHiUiHRsjER1O
    OitGFQIbQCtBVE9AHg8eJSIdGyMRHU46K0YWAhs/K0FUAU8pHCImDggpHCImDgADABX/9gLNAsYA
    DwAfADsA77EGZERLsAxQWEA5AAUGCAYFcAAIBwcIbgAAAAIEAAJnAAQABgUEBmcABwwBCQMHCWgL
    AQMBAQNXCwEDAwFfCgEBAwFPG0uwDVBYQDoABQYIBgVwAAgHBggHfAAAAAIEAAJnAAQABgUEBmcA
    BwwBCQMHCWgLAQMBAQNXCwEDAwFfCgEBAwFPG0A7AAUGCAYFCH4ACAcGCAd8AAAAAgQAAmcABAAG
    BQQGZwAHDAEJAwcJaAsBAwEBA1cLAQMDAV8KAQEDAU9ZWUAiICAQEAAAIDsgOjc2NDIvLSsqJyUQ
    HxAeGBYADwAOJg0HFSuxBgBEBCYmNTQ2NjMyFhYVFAYGIz4CNTQmJiMiBgYVFBYWMyYmNTU0NjMy
    FhUVIzU0IyIVFRQzMjU1MxUUBiMBDp9aWp9jY59aWp9jT35HR35PT35HR35PPDk5ODg5SCcnJydI
    OTgKXqRmZqReXqRmZqReRkqFU1OFSkqFU1OFSkY/O8I8QEA8JCowMMwvLzw4Oz8ABAAV//YCzQLG
    AA8AHwA5AEMAaLEGZERAXScBBggBSgcBBQYDBgUDfgAAAAIEAAJnAAQACQgECWcMAQgABgUIBmcL
    AQMBAQNXCwEDAwFfCgEBAwFPOzoQEAAAQkA6QztDOTg3NS8uIiAQHxAeGBYADwAOJg0HFSuxBgBE
    BCYmNTQ2NjMyFhYVFAYGIz4CNTQmJiMiBgYVFBYWMwMzMhYVFRQHFRYWFRUUFyMmJjU1NCYjIxUj
    NzI2NTU0JiMjFQEOn1pan2Njn1pan2NPfkdHfk9PfkdHfk9udDo3NBwYCU4EAxgbGkxrFhgTFiQK
    XqRmZqReXqRmZqReRkqFU1OFSkqFU1OFSgH4NzkJRhcCDDIoMycUCxUcMyIcrfMXHA0aGXMAAAQA
    Ff/2As0CxgAPAB8AKQAzAFdAVAAGBQMFBgN+AAAAAgQAAmcABAAIBwQIZwsBBwAFBgcFZwoBAwEB
    A1cKAQMDAV8JAQEDAU8rKhAQAAAyMCozKzMpKCclIiAQHxAeGBYADwAOJgwKFSsEJiY1NDY2MzIW
    FhUUBgYjPgI1NCYmIyIGBhUUFhYzAzMyFRUUIyMVIzcyNjU1NCYjIxUBDp9aWp9jY59aWp9jT35H
    R35PT35HR35PXXRxcShMcBYTExYkCl6kZmakXl6kZmakXkZKhVNThUpKhVNThUoB73ApcKPpGRoX
    Ghl9AAAAAgAKAVgCMQK8AAcAFwA0QDEUEAoDAwABSggHBgMDAAOEBQQCAQAAAVUFBAIBAQBdAgEA
    AQBNExMRExEREREQCQodKxMjNTMVIxEjEzMXMzczESMRIwMjAyMRI1NJ2ElGuWkpAihpQgI2NjYC
    PQJ8QED+3AFk4uL+nAEP/vEBD/7xAAAAAgBJAcgBRwLGAAsAFwA4sQZkREAtAAAAAgMAAmcFAQMB
    AQNXBQEDAwFfBAEBAwFPDAwAAAwXDBYSEAALAAokBgcVK7EGAEQSJjU0NjMyFhUUBiM2NjU0JiMi
    BhUUFjOTSko1NUpKNRYfHxYWHh4WAchKNTVKSjU1SkseFhYfHxYWHgAAAQDN/zgBJwMgAAMAGEAV
    AAABAQBVAAAAAV0AAQABTREQAgcWKxMzESPNWloDIPwYAAAAAAIAzf84AScDIAADAAcAIkAfAAAA
    AQIAAWUAAgMDAlUAAgIDXQADAgNNEREREAQHGCsTMxEjFTMRI81aWlpaAyD+cMj+cAAAAAEAFv+f
    AXoCvAALACFAHgMBAQQBAAUBAGUABQUCXQACAhcFTBEREREREAYHGisTIzUzNTMVMxUjESOWgIBk
    gIBkAaNfurpf/fwAAAACAAv/9gGDAsYAIAAqAG1ADioTCQcEAgQGAwIBAgJKS7ALUFhAIAACBAEB
    AnAAAAAEAgAEZwABAwMBVwABAQNgBQEDAQNQG0AhAAIEAQQCAX4AAAAEAgAEZwABAwMBVwABAQNg
    BQEDAQNQWUAOAAAnJQAgAB8TKCwGChcrFiY1NQYHByc2NxE0NjMyFhUVFAcVFBYzMjY1NTMVFAYj
    EjU1NCYjIgYVFatMDAYcJi8lTEdFTLYQFhURakxFJxEVFhAKTEQoBgQPUhgYAR5FTExFFaKJZB8Y
    GR4+SURMAclfDh4ZGR69AAAAAQAW/58BegK8ABMAMEAtBQEDBgECAQMCZQcBAQgBAAkBAGUACQkE
    XQAEBBcJTBMSEREREREREREQCgcdKzcjNTM1IzUzNTMVMxUjFTMVIxUjloCAgIBkgICAgGRZX+tf
    urpf61+6AAACACH/9gMZAsYAHQAtAE9ATCshIAMGBRAPAgMBAkoAAwECAQMCfgAAAAUGAAVnCAEG
    AAEDBgFlAAIEBAJXAAICBF8HAQQCBE8eHgAAHi0eLSclAB0AHBIoFCYJChgrBCYmNTQ2NjMyFhYV
    FSEiFRUUFhcWFjMyNjczBgYjEzI1NTQnJiYjIgcGFRUUMwE2rmdnrmdnrmf9mwgJAiV8R0h+Ljg2
    n1nsBwwqeEN+agsICmGmYWGlYmKlYQkHwQcMAjU3QDhCTAFzB8QIDjE1agsLwAcAAAQAKQAAAnEC
    vAALABkAJQApAExASQgBBAACAQcGAkoABAAGBwQGZwsBBwoBBQgHBWcBAQAAF0sACAgCXQkDAgIC
    GAJMGhoMDCkoJyYaJRokHx0MGQwYJhMRExAMBxkrEzMTMxEzESMDIxEjJCY1NTQ2MzIWFRUUBiM2
    NTU0IyIGFRUUFjMHMxUjKYpSAl1xagJeAas3NzMzNzczJCQSEhISatTUArz+UwGt/UQCBf37bTo1
    mzU6OjWbNTpAK6MrFBejFxRpRAAAAQATAa4BewK8AAYAIbEGZERAFgQBAQABSgAAAQCDAgEBAXQS
    ERADBxcrsQYARBMzEyMnByOiSo9aWlpaArz+8qqqAAACABUBUAIyAsIAJQA1AOpACzIuAgMEKAEA
    AwJKS7AYUFhAOQcBBgIEAgYEfgADBAAEA3AAAAEBAG4KCQIIAQUBCAV+AAIABAMCBGcAAQgFAVcA
    AQEFYAsBBQEFUBtLsB1QWEA6BwEGAgQCBgR+AAMEAAQDcAAAAQQAAXwKCQIIAQUBCAV+AAIABAMC
    BGcAAQgFAVcAAQEFYAsBBQEFUBtAOwcBBgIEAgYEfgADBAAEAwB+AAABBAABfAoJAggBBQEIBX4A
    AgAEAwIEZwABCAUBVwABAQVgCwEFAQVQWVlAGAAANTQxMC0sKyonJgAlACQiEykiEwwKGSsSJjU1
    MxUUMzI1NCYnJiY1NDYzMhYVFSM1NCMiFRQWFxYWFRQGIxMzFzM3MxEjESMDIwMjESNJNEMhIRkj
    Kh00MDEzQiAgGCQpHTQxk2kpAihpQgI2NjYCPQFQLiwWFSEiGB0SFjMmKzUvKwsKISAWGxQXNCYt
    NQFs4uL+nAEP/vEBD/7xAAAC/4IC6wB+A1EAAwAHACWxBmREQBoCAQABAQBVAgEAAAFdAwEBAAFN
    EREREAQHGCuxBgBEAzMVIzczFSN+YmKaYmIDUWZmZgAB/84C6wAyA1EAAwAgsQZkREAVAAABAQBV
    AAAAAV0AAQABTREQAgcWK7EGAEQDMxUjMmRkA1FmAAH/fgLrADwDXgADACCxBmREQBUAAAEBAFUA
    AAABXQABAAFNERACBxYrsQYARAMzFyOCeEZTA15zAAAAAAH/xALrAIIDXgADACCxBmREQBUAAAEB
    AFUAAAABXQABAAFNERACBxYrsQYARBMzByMKeGtTA15zAAAAAAL/fgLrAMgDXgADAAcAJbEGZERA
    GgIBAAEBAFUCAQAAAV0DAQEAAU0REREQBAcYK7EGAEQDMwcjNzMHIzxvaE3bb2hNA15zc3MAAAAB
    /80B7gAzArwABgA7tQQBAAEBSkuwDFBYQBEAAgAAAm8AAAABXQABARcATBtAEAACAAKEAAAAAV0A
    AQEXAExZtRIREAMHFysDIzUzFQcjCyhmLi0CVmZbcwAAAAH/egLrAIYDXgAGACGxBmREQBYEAQEA
    AUoAAAEAgwIBAQF0EhEQAwcXK7EGAEQDMxcjJwcjNGhSUzMzUwNeczc3AAAAAf96AusAhgNeAAYA
    IbEGZERAFgIBAgABSgEBAAIAgwACAnQREhADBxcrsQYARAMzFzczByOGUzMzU1JoA143N3MAAAAB
    /4oC5wB2A14ADQBRsQZkREuwGlBYQBgCAQABAQBuAAEDAwFXAAEBA2AEAQMBA1AbQBcCAQABAIMA
    AQMDAVcAAQEDYAQBAwEDUFlADAAAAA0ADBIiEgUHFyuxBgBEAiYnMxYWMzI2NzMGBiM4PAJBBBkX
    GBoEQQI9OALnPjkbFRUbOD8AAAAAAv+nAuAAWQOQAAsAFwA4sQZkREAtAAAAAgMAAmcFAQMBAQNX
    BQEDAwFfBAEBAwFPDAwAAAwXDBYSEAALAAokBgcVK7EGAEQCJjU0NjMyFhUUBiM2NjU0JiMiBhUU
    FjMmMzMmJjMzJg4SEg4OEhIOAuAzJSUzMyUlMzUTEBATExAQEwAAAf91AucAiwNiABkAOLEGZERA
    LQ0BAQABSgwBAEgZAQJHAAEDAgFXAAAAAwIAA2cAAQECXwACAQJPJCUkIgQHGCuxBgBEAzY2MzIW
    FxYWMzI2NxcGBiMiJicmJiMiBgeLEywcEhsPCREIDBIKNRMsHBIbDwkRCAwSCgMHKykKCQUIEhUg
    KykKCQUIEhUAAAAAAf+NAvQAcwNCAAMAILEGZERAFQAAAQEAVQAAAAFdAAEAAU0REAIHFiuxBgBE
    AzMVI3Pm5gNCTgAB/9IC6wAuA30ABgBNsQZkRLUAAQIBAUpLsBhQWEAWAAABAQBuAAECAgFVAAEB
    Al4AAgECThtAFQAAAQCDAAECAgFVAAEBAl4AAgECTlm1ERERAwcXK7EGAEQDNzMHMxUjLisnGiRc
    Az1ANlwAAAAAAf/S/0MALv/VAAYATbEGZES1BAEAAQFKS7AYUFhAFgACAAACbwABAAABVQABAQBd
    AAABAE0bQBUAAgAChAABAAABVQABAQBdAAABAE1ZtRIREAMHFyuxBgBEByM1MxUHIwokXCsnh1xS
    QAAAAf+Y/20AXgAOABgApbEGZERLsB9QWEAnAAQDAgAEcAABAAUAAXAAAwACAAMCZwAAAQUAVQAA
    AAVgBgEFAAVQG0uwLVBYQCgABAMCAwQCfgABAAUAAXAAAwACAAMCZwAAAQUAVQAAAAVgBgEFAAVQ
    G0ApAAQDAgMEAn4AAQAFAAEFfgADAAIAAwJnAAABBQBVAAAABWAGAQUABVBZWUAOAAAAGAAXERIU
    IxMHBxkrsQYARAYmNTUzFRQWMzI2NTQmIyM1MxUyFhUUBiM2MkoNCQ4MEhMFMSIjMjSTGiAKCAoK
    Cw0ODEc1FhklGAAB/7L/bQBOAAQAEQBZsQZkRLUOAQIBAUpLsA1QWEAYAAEAAgABcAAAAQIAVQAA
    AAJfAwECAAJPG0AZAAEAAgABAn4AAAECAFUAAAACXwMBAgACT1lACwAAABEAECQUBAcWK7EGAEQG
    JjU0NzMGFRQWMzI2NxUGBiMfL0wsIxQPEBEDER0WkyAeNSQbIw0PBQE4BwQAAf+VAS8AawGNAAMA
    ILEGZERAFQAAAQEAVQAAAAFdAAEAAU0REAIHFiuxBgBEAzMVI2vW1gGNXgAB/y8BMQDRAYsAAwAg
    sQZkREAVAAABAQBVAAAAAV0AAQABTREQAgcWK7EGAEQDIRUh0QGi/l4Bi1oAAAAB/1n/5ACnAtgA
    AwAGswMBATArBwEXAacBHDL+5AcC3xX9IQAB/0//5gCxAtYAAwAGswMBATArIwEXAbEBJjz+2gLW
    Gv0qAAAB/8sB7gA1ArwABgBNsQZkRLUEAQABAUpLsAxQWEAWAAIAAAJvAAEAAAFVAAEBAF0AAAEA
    TRtAFQACAAKEAAEAAAFVAAEBAF0AAAEATVm1EhEQAwcXK7EGAEQDIzUzFQcjCypqMC0CUmpfb///
    AIcC9AFtA0IAAwHeAPoAAAAA//8AvgLrAXwDXgADAdYA+gAAAAD//wCEAucBcANeAAMB2wD6AAAA
    AP//AHQC6wGAA14AAwHaAPoAAAAA//8Al/9tAV0ADgADAeEA/wAAAAD//wB0AusBgANeAAMB2QD6
    AAAAAP//AHwC6wF4A1EAAwHTAPoAAAAA//8AyALrASwDUQADAdQA+gAAAAD//wB4AusBNgNeAAMB
    1QD6AAAAAP//AHgC6wHCA14AAwHXAPoAAAAA//8AhwL0AW0DQgADAd4A+gAAAAD//wCs/20BSAAE
    AAMB4gD6AAAAAP//AKEC4AFTA5AAAwHcAPoAAAAA//8AbwLnAYUDYgADAd0A+gAAAAD//wDHAe4B
    LQK8AAMB2AD6AAAAAP//ABP/yQF7AukAAgGfAAAAAQAAAAIAAOO6+H9fDzz1AAcD6AAAAADWnrim
    AAAAANagBof/L/84AyoDkAAAAAcAAgAAAAAAAAABAAADhP7UAAADTf8v/y8DKgABAAAAAAAAAAAA
    AAAAAAAB+QLiADYAAAAAAKAAAACgAAABkQAMAZEADAGRAAwBkQAMAZEADAGRAAwBkQAMAZEADAGR
    AAwBkQAMAkQACgJEAAoBlAApAZQAKQF/ACIBfwAiAX8AIgF/ACIBfwAiAX8AIgGWACkBpwAKAZYA
    KQGnAAoBlgApAWsAKQFrACkBawApAWsAKQFrACkBawApAWsAKQFrACkBawApAWsAKQFYACkBWAAp
    AYcAIQGHACEBhwAhAYcAIQGHACEBpAApAbYACgGkACkAwAApAckAKQDAACQAwP/qAMD/2gDA/+IA
    wAApAMD/3gDA/+0AwAARAMD/1QEJABABCQAQAQkAEAGeACkBngApAVgAKQFYACkBWAApAVgAKQFX
    ACkBbAAKAhoAKQIaACkBqwApAasAKQGrACkBqwApAasAKQGrACkBkAAhAZAAIQGQACEBkAAhAZAA
    IQGQACEBkAAhAZAAIQGQABcBkAAXAZAAIQJBACEBggApAYIAKQGCACkBkAAhAZMAKQGTACkBkwAp
    AZMAKQF0ABYBdAAWAXQAFgF0ABYBdAAWAXQAFgF0ABYBlwApAWwADAFsAAwBbAAMAWwADAFsAAwB
    bAAMAZIAJQGSACUBkgAlAZIAJQGSACUBkgAlAZIAJQGSACUBkgAlAZIAJQGSACUBfgAMAi0ADwIt
    AA8CLQAPAi0ADwItAA8BlgALAYoACQGKAAkBigAJAYoACQGKAAkBagATAWoAEwFqABMBagATAZEA
    DAGRAAwBkQAMAZEADAGRAAwBkQAMAZEADAGRAAwBkQAMAZEADAJEAAoCRAAKAZQAKQGUACkBfwAi
    AX8AIgF/ACIBfwAiAX8AIgF/ACIBlgApAacACgGWACkBpwAKAZYAKQFrACkBawApAWsAKQFrACkB
    awApAWsAKQFrACkBawApAWsAKQFrACkBWAApAVgAKQGHACEBhwAhAYcAIQGHACEBhwAhAaQAKQG2
    AAoBpAApAMAAKQDAACkAwAAkAMD/6gDA/9oAwP/iAMAAKQDA/94ByQApAMD/7QDAABEAwP/VAQkA
    EAEJABABCQAQAQkAEAGeACkBngApAZ4AKQFYACkBWAApAVgAKQFYACkBVwApAWwACgIaACkCGgAp
    AasAKQGrACkCHgAEAasAKQGrACkBqwApAasAKQGQACEBkAAhAZAAIQGQACEBkAAhAZAAIQGQACEB
    kAAhAZAAFwGQABcBkAAhAkEAIQGCACkBggApAYIAKQGQACEBkwApAZMAKQGTACkBkwApAXQAFgF0
    ABYBdAAWAXQAFgF0ABYBdAAWAXQAFgGXACkBbAAMAWwADAFsAAwBbAAMAWwADAFsAAwBkgAlAZIA
    JQGSACUBkgAlAZIAJQGSACUBkgAlAZIAJQGSACUBkgAlAZIAJQF+AAwCLQAPAi0ADwItAA8CLQAP
    Ai0ADwGWAAsBigAJAYoACQGKAAkBigAJAYoACQFqABMBagATAWoAEwFqABMBGAAeARoAIwGRAAwB
    kgAiAZUAKQHEAA4BkAAhAZAAUAGQACcBkAAhAZAADwGQACYBkAAkAZAAIgGQABwBkAAeAZAAIQEj
    ABIBdAAYAXYAFAGOAA4BfgAcAYkAIQFkAAwBjAAaAYkAGgGQACEBIwASAXQAGAF2ABQBjgAOAX4A
    HAGJACEBZAAMAYwAGgGJABoBGgAjARoAOgEaACYBGgAiARoAFwEaACYBGgAlARoAIwEaACABGgAh
    ARoAIwEaADoBGgAmARoAIgEaABcBGgAmARoAJQEaACMBGgAgARoAIQEaACMBGgA6ARoAJgEaACIB
    GgAXARoAJgEaACUBGgAjARoAIAEaACEBGgAjARoAOgEaACYBGgAiARoAFwEaACYBGgAlARoAIwEa
    ACABGgAhAFn/ggKNADoCjQA6Ao0AJgKNADoCjQAiAo0AOgKNACICjQAmAo0AIwGmAA8BhQAJALwA
    KQEsACMAvAApALwAKQH0AB8A0gAyANIAMgGcABAAvAApAWsAEwFrABQBUAAmALwAJgC8ACMBhQAJ
    ASwAAAEUABUBFAAZARQAOwEUACMBFAA1ARQAIwH0AAABLAAAAZAAAAEOABkBDgAZAVAADgFPABEA
    vAAOALwAEQFQACMBUAApAVAAIwC8ACkAvAAjALwAKgH0AAABLAAAAZAAAAC8AAAAoAAAAAAAAAGQ
    ACoBkAAfAZAAJAGQABcBkAATAZAAHAGQACMBkAALANwALgGQABEBkAAbAZAAGwGQACgBkAAbAZAA
    JQGQACUBkAA2AZAAKAGQADMBkAArAZAAJAGQAAwBkAAMAZAAFgKDABoC3gA2AZAANgGSACIBkQAM
    AdEAMQGbABkB2wAQAZUAKQGsACECTQAjA00AIwGQABQCegAXArgAGQGhACIBwQAaAZAAFwLiABUC
    4gAVAuIAFQJWAAoBkABJAfQAzQH0AM0BkAAWAZwACwGQABYDNQAhApUAKQGQABMCVwAVAAD/ggAA
    /84AAP9+AAD/xAAA/34AAP/NAAD/egAA/3oAAP+KAAD/pwAA/3UAAP+NAAD/0gAA/9IAAP+YAAD/
    sgAA/5UAAP8vAAD/WQAA/08AAP/LAfQAhwH0AL4B9ACEAfQAdAH0AJcB9AB0AfQAfAH0AMgB9AB4
    AfQAeAH0AIcB9ACsAfQAoQH0AG8B9ADHAZAAEwH0AAAAAAAAAAAARABEAEQARAB0AIAAjACYAKQA
    sAC8AMgA1ADgASIBLgGCAY4B6AH0AgACDAIYAiQCWAJoAnQChAKQAroCxgLSAt4C6gL2AwIDDgMa
    AyYDTANYA7YDwgPOA9oD5gQOBCAELARCBE4EWgRmBHIEfgSKBJYEogSuBLoE6AT0BQAFKgU2BVIF
    XgVqBXYFngXOBfwGCAYwBjwGSAZUBpYGogbeBuoG9gcCBw4HGgcmBzIHPgdOB1oHoAfYB+QIIAhw
    CL4IygjWCOIJYgluCXoJhgmSCZ4JqgnsCgwKPgpKClYKYgpuCpwKqAq0CsAKzArYCuQK8Ar8CwgL
    FAs2C2YLcgt+C4oLlgvCC+gL9AwADAwMGAxCDE4MWgxmDG4MegyGDJIMngyqDLYMwgzODNoM4gzu
    DPYNAg0KDRYNIg0uDToNRg1ODV4Nag16DYYNjg2aDaYNsg2+DcoN1g3iDe4N+g4CDg4OFg4iDi4O
    Og5GDk4OYA5sDnQOfA6IDpQOoA6sDrgOxA7QDtwO6A70DvwPBA8QDxwPJA8wDzgPQA9MD1gPZA9s
    D3QPfA+ID5APnA+oD7QPwA/ID9QP3A/oD/QQABAMEBgQJBAwEDwQTBBYEGAQaBB0EHwQhBCMEJgQ
    pBCwELgQxBDQENwQ6BD0EQARCBEQERgRJBEwETwRSBFQEVwRaBF0EYARjBGYEaQRsBG8EcgR0BHY
    EeQR8BH8EggSEBIYEiQSMBI8EkgSUBJcEmgSdBMWE14TihPSFDYUXhSaFL4VEhWqFd4WSha4FtoX
    PheuF7YXvhfGF84X1hfeF+YX7hf2F/4YBhgOGBYYHhgmGC4YNhg+GEYYThiIGKoY/hmUGdoaRBqY
    GrgbGBtsG6QbxhwYHKoc3h1GHZgduB4WHmgeoB7CHxQfph/aIEIglCC0IRIhZCGeIcAiEiKmItoj
    QiOUI7QkFCRmJH4kjiSeJK4kviTOJN4k7iT+JQ4lOiVSJWolkCWwJdwmACYmJkwmoia4JxgneieY
    J64n6igCKB4oaCiwKNIo9CkoKVgpcimMKaYpvinGKfIqJCpEKmYqoirOKworKCtWK14rXiteK14r
    XiteK14r3iw+LJotRC2+LgYudi62Ls4u5i8OLygvRC9yL5Yv6jAAMBQwPjBqMJoxEDFYMYgx/jJg
    Mp4ypjKuMtAzAjMsMzQzvDRmNT41ZDWuNpo3QjdwOBg44DlyOeg6KjpsOoY6qjrQO0Q7eDviPEY8
    aD0oPUw9aD2GPaQ9yj34Pho+PD6APsI/Cj8mP14/lEAKQFRAcECOQKBAskDoQPJA/EEGQRBBGkEk
    QS5BOEFCQUxBVkFgQWpBdEF+QYZBhkGGQYYAAQAAAfsATAAHAGAABQACACgAOgCLAAAAgw1tAAMA
    AQAAAB4BbgABAAAAAAAAACAAAAABAAAAAAABAAoAIAABAAAAAAACAAcAKgABAAAAAAADABwAMQAB
    AAAAAAAEABIATQABAAAAAAAFAA0AXwABAAAAAAAGABEAbAABAAAAAAAHACkAfQABAAAAAAAIABEA
    pgABAAAAAAAJABEAtwABAAAAAAAKADcAyAABAAAAAAALABUA/wABAAAAAAAMABUBFAABAAAAAAAN
    AJABKQABAAAAAAAOABoBuQADAAEECQAAAEAB0wADAAEECQABABQCEwADAAEECQACAA4CJwADAAEE
    CQADADgCNQADAAEECQAEACQCbQADAAEECQAFABoCkQADAAEECQAGACICqwADAAEECQAHAFICzQAD
    AAEECQAIACIDHwADAAEECQAJACIDQQADAAEECQAKAG4DYwADAAEECQALACoD0QADAAEECQAMACoD
    +wADAAEECQANASAEJQADAAEECQAOADQFRUNvcHlyaWdodCCpIDIwMTAgYnkgRGhhcm1hIFR5cGUu
    QmViYXMgTmV1ZVJlZ3VsYXIyLjAwMDtkaHJtO0JlYmFzTmV1ZS1SZWd1bGFyQmViYXMgTmV1ZSBS
    ZWd1bGFyVmVyc2lvbiAyLjAwMEJlYmFzTmV1ZS1SZWd1bGFyQmViYXMgTmV1ZSBpcyBhIHRyYWRl
    bWFyayBvZiBEaGFybWEgVHlwZS5SeW9pY2hpIFRzdW5la2F3YVJ5b2ljaGkgVHN1bmVrYXdhRGVz
    aWduZWQgYnkgUnlvaWNoaSBUc3VuZWthd2EgZnJvbSBEaGFybWEgVHlwZSBpbiAyMDEwLmh0dHA6
    Ly9kaGFybWF0eXBlLmNvbWh0dHA6Ly9kaGFybWF0eXBlLmNvbVRoaXMgRm9udCBTb2Z0d2FyZSBp
    cyBsaWNlbnNlZCB1bmRlciB0aGUgU0lMIE9wZW4gRm9udCBMaWNlbnNlLCBWZXJzaW9uIDEuMS4g
    VGhpcyBsaWNlbnNlIGlzIGF2YWlsYWJsZSB3aXRoIGEgRkFRIGF0OiBodHRwOi8vc2NyaXB0cy5z
    aWwub3JnL09GTGh0dHA6Ly9zY3JpcHRzLnNpbC5vcmcvT0ZMAEMAbwBwAHkAcgBpAGcAaAB0ACAA
    qQAgADIAMAAxADAAIABiAHkAIABEAGgAYQByAG0AYQAgAFQAeQBwAGUALgBCAGUAYgBhAHMAIABO
    AGUAdQBlAFIAZQBnAHUAbABhAHIAMgAuADAAMAAwADsAZABoAHIAbQA7AEIAZQBiAGEAcwBOAGUA
    dQBlAC0AUgBlAGcAdQBsAGEAcgBCAGUAYgBhAHMAIABOAGUAdQBlACAAUgBlAGcAdQBsAGEAcgBW
    AGUAcgBzAGkAbwBuACAAMgAuADAAMAAwAEIAZQBiAGEAcwBOAGUAdQBlAC0AUgBlAGcAdQBsAGEA
    cgBCAGUAYgBhAHMAIABOAGUAdQBlACAAaQBzACAAYQAgAHQAcgBhAGQAZQBtAGEAcgBrACAAbwBm
    ACAARABoAGEAcgBtAGEAIABUAHkAcABlAC4AUgB5AG8AaQBjAGgAaQAgAFQAcwB1AG4AZQBrAGEA
    dwBhAFIAeQBvAGkAYwBoAGkAIABUAHMAdQBuAGUAawBhAHcAYQBEAGUAcwBpAGcAbgBlAGQAIABi
    AHkAIABSAHkAbwBpAGMAaABpACAAVABzAHUAbgBlAGsAYQB3AGEAIABmAHIAbwBtACAARABoAGEA
    cgBtAGEAIABUAHkAcABlACAAaQBuACAAMgAwADEAMAAuAGgAdAB0AHAAOgAvAC8AZABoAGEAcgBt
    AGEAdAB5AHAAZQAuAGMAbwBtAGgAdAB0AHAAOgAvAC8AZABoAGEAcgBtAGEAdAB5AHAAZQAuAGMA
    bwBtAFQAaABpAHMAIABGAG8AbgB0ACAAUwBvAGYAdAB3AGEAcgBlACAAaQBzACAAbABpAGMAZQBu
    AHMAZQBkACAAdQBuAGQAZQByACAAdABoAGUAIABTAEkATAAgAE8AcABlAG4AIABGAG8AbgB0ACAA
    TABpAGMAZQBuAHMAZQAsACAAVgBlAHIAcwBpAG8AbgAgADEALgAxAC4AIABUAGgAaQBzACAAbABp
    AGMAZQBuAHMAZQAgAGkAcwAgAGEAdgBhAGkAbABhAGIAbABlACAAdwBpAHQAaAAgAGEAIABGAEEA
    UQAgAGEAdAA6ACAAaAB0AHQAcAA6AC8ALwBzAGMAcgBpAHAAdABzAC4AcwBpAGwALgBvAHIAZwAv
    AE8ARgBMAGgAdAB0AHAAOgAvAC8AcwBjAHIAaQBwAHQAcwAuAHMAaQBsAC4AbwByAGcALwBPAEYA
    TAAAAgAAAAAAAP/YAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAH7AAABAgACAAMAJADJAQMAxwBiAK0B
    BAEFAGMArgCQAQYAJQEHACYA/QD/AGQBCAEJACcA6QEKAQsBDAAoAGUBDQEOAMgAygEPAMsBEAER
    ACkBEgAqAPgBEwEUARUAKwEWARcALAEYAMwBGQDNAM4A+gDPARoBGwEcAC0BHQEeAC4BHwAvASAB
    IQEiASMA4gAwASQAMQElASYBJwEoAGYAMgDQASkA0QBnANMBKgErAJEBLACvALAAMwEtAO0ANAA1
    AS4BLwEwADYBMQDkAPsBMgEzATQBNQA3ATYBNwE4ATkBOgA4ANQBOwDVAGgA1gE8AT0BPgE/AUAA
    OQA6AUEBQgFDAUQAOwA8AOsBRQC7AUYAPQFHAOYBSABEAGkBSQBrAGwAagFKAUsAbgBtAKABTABF
    AU0ARgD+AQAAbwFOAU8ARwDqAVABAQFRAEgAcAFSAVMAcgBzAVQAcQFVAVYASQFXAEoA+QFYAVkB
    WgBLAVsBXABMANcAdAFdAHYAdwFeAHUBXwFgAWEBYgBNAWMBZAFlAE4BZgFnAE8BaAFpAWoBawDj
    AFABbABRAW0BbgFvAXABcQB4AFIAeQFyAHsAfAB6AXMBdAChAXUAfQCxAFMBdgDuAFQAVQF3AXgB
    eQBWAXoA5QD8AXsBfAF9AIkAVwF+AX8BgAGBAYIAWAB+AYMAgACBAH8BhAGFAYYBhwGIAFkAWgGJ
    AYoBiwGMAFsAXADsAY0AugGOAF0BjwDnAZAAnQCeAZEBkgGTAJsAEwAUABUAFgAXABgAGQAaABsA
    HAGUAZUBlgGXAZgBmQGaAZsBnAGdAZ4BnwGgAaEBogGjAaQBpQGmAacBqAGpAaoBqwGsAa0BrgGv
    AbABsQGyAbMBtAG1AbYBtwG4AbkBugG7AbwBvQG+Ab8BwAHBAcIBwwHEAcUBxgHHAcgByQHKAcsB
    zAHNAc4BzwC8APQB0AHRAPUA9gHSAdMB1AHVAA0APwDDAIcAHQAPAKsABACjAAYAEQAiAKIABQAK
    AB4AEgBCAF4AYAA+AEAACwAMALMAsgHWABAB1wCpAKoAvgC/AMUAtAC1ALYAtwDEAdgB2QHaAdsB
    3AHdAIQAvQAHAd4ApgHfAIUAlgHgAeEADgDvAPAAuAAgAI8AIQAfAJUAlACTAKcAYQCkAJIB4gCc
    AeMB5ACaAJkApQHlAJgACADGALkB5gAjAAkAiACGAIsAigHnAIwAgwBfAOgAggHoAMIB6QHqAEEB
    6wHsAe0B7gHvAfAB8QHyAfMB9AH1AfYB9wH4AfkB+gH7AfwB/QH+Af8CAAIBAI0A2wDhAN4A2ACO
    ANwAQwDfANoA4ADdANkCAgIDAgQCBQIGBE5VTEwGQWJyZXZlB0FtYWNyb24HQW9nb25lawdBRWFj
    dXRlB3VuaTFFMDILQ2NpcmN1bWZsZXgKQ2RvdGFjY2VudAZEY2Fyb24GRGNyb2F0B3VuaTFFMEEG
    RWJyZXZlBkVjYXJvbgpFZG90YWNjZW50B0VtYWNyb24HRW9nb25lawd1bmkxRTFFC0djaXJjdW1m
    bGV4DEdjb21tYWFjY2VudApHZG90YWNjZW50BEhiYXILSGNpcmN1bWZsZXgCSUoGSWJyZXZlB0lt
    YWNyb24HSW9nb25lawZJdGlsZGULdW5pMDBBNDAzMDELSmNpcmN1bWZsZXgMS2NvbW1hYWNjZW50
    BkxhY3V0ZQZMY2Fyb24MTGNvbW1hYWNjZW50BExkb3QHdW5pMUU0MAZOYWN1dGUGTmNhcm9uDE5j
    b21tYWFjY2VudANFbmcGT2JyZXZlDU9odW5nYXJ1bWxhdXQHT21hY3JvbgtPc2xhc2hhY3V0ZQd1
    bmkxRTU2BlJhY3V0ZQZSY2Fyb24MUmNvbW1hYWNjZW50BlNhY3V0ZQtTY2lyY3VtZmxleAxTY29t
    bWFhY2NlbnQHdW5pMUU2MAd1bmkxRTlFBFRiYXIGVGNhcm9uB3VuaTAxNjIHdW5pMDIxQQd1bmkx
    RTZBBlVicmV2ZQ1VaHVuZ2FydW1sYXV0B1VtYWNyb24HVW9nb25lawVVcmluZwZVdGlsZGUGV2Fj
    dXRlC1djaXJjdW1mbGV4CVdkaWVyZXNpcwZXZ3JhdmULWWNpcmN1bWZsZXgGWWdyYXZlBlphY3V0
    ZQpaZG90YWNjZW50BmFicmV2ZQdhbWFjcm9uB2FvZ29uZWsHYWVhY3V0ZQd1bmkxRTAzC2NjaXJj
    dW1mbGV4CmNkb3RhY2NlbnQGZGNhcm9uB3VuaTFFMEIGZWJyZXZlBmVjYXJvbgplZG90YWNjZW50
    B2VtYWNyb24HZW9nb25lawd1bmkxRTFGC2djaXJjdW1mbGV4DGdjb21tYWFjY2VudApnZG90YWNj
    ZW50BGhiYXILaGNpcmN1bWZsZXgGaWJyZXZlCWkubG9jbFRSSwJpagdpbWFjcm9uB2lvZ29uZWsG
    aXRpbGRlB3VuaTAyMzcLdW5pMDA2QTAzMDELamNpcmN1bWZsZXgMa2NvbW1hYWNjZW50DGtncmVl
    bmxhbmRpYwZsYWN1dGUGbGNhcm9uDGxjb21tYWFjY2VudARsZG90B3VuaTFFNDEGbmFjdXRlC25h
    cG9zdHJvcGhlBm5jYXJvbgxuY29tbWFhY2NlbnQDZW5nBm9icmV2ZQ1vaHVuZ2FydW1sYXV0B29t
    YWNyb24Lb3NsYXNoYWN1dGUHdW5pMUU1NwZyYWN1dGUGcmNhcm9uDHJjb21tYWFjY2VudAZzYWN1
    dGULc2NpcmN1bWZsZXgMc2NvbW1hYWNjZW50B3VuaTFFNjEEdGJhcgZ0Y2Fyb24HdW5pMDE2Mwd1
    bmkwMjFCB3VuaTFFNkIGdWJyZXZlDXVodW5nYXJ1bWxhdXQHdW1hY3Jvbgd1b2dvbmVrBXVyaW5n
    BnV0aWxkZQZ3YWN1dGULd2NpcmN1bWZsZXgJd2RpZXJlc2lzBndncmF2ZQt5Y2lyY3VtZmxleAZ5
    Z3JhdmUGemFjdXRlCnpkb3RhY2NlbnQHdW5pMDM5NAd1bmkwM0E5B3VuaTAzQkMIemVyby5hbHQH
    b25lLmFsdAd0d28uYWx0CXRocmVlLmFsdAhmb3VyLmFsdAhmaXZlLmFsdAdzaXguYWx0CXNldmVu
    LmFsdAllaWdodC5hbHQIbmluZS5hbHQHemVyby5sZgZvbmUubGYGdHdvLmxmCHRocmVlLmxmB2Zv
    dXIubGYHZml2ZS5sZgZzaXgubGYIc2V2ZW4ubGYIZWlnaHQubGYHbmluZS5sZgd1bmkyMDgwB3Vu
    aTIwODEHdW5pMjA4Mgd1bmkyMDgzB3VuaTIwODQHdW5pMjA4NQd1bmkyMDg2B3VuaTIwODcHdW5p
    MjA4OAd1bmkyMDg5CXplcm8uZG5vbQhvbmUuZG5vbQh0d28uZG5vbQp0aHJlZS5kbm9tCWZvdXIu
    ZG5vbQlmaXZlLmRub20Ic2l4LmRub20Kc2V2ZW4uZG5vbQplaWdodC5kbm9tCW5pbmUuZG5vbQl6
    ZXJvLm51bXIIb25lLm51bXIIdHdvLm51bXIKdGhyZWUubnVtcglmb3VyLm51bXIJZml2ZS5udW1y
    CHNpeC5udW1yCnNldmVuLm51bXIKZWlnaHQubnVtcgluaW5lLm51bXIHdW5pMjA3MAd1bmkwMEI5
    B3VuaTAwQjIHdW5pMDBCMwd1bmkyMDc0B3VuaTIwNzUHdW5pMjA3Ngd1bmkyMDc3B3VuaTIwNzgH
    dW5pMjA3OQd1bmkyMTUzB3VuaTIxNTQJb25lZWlnaHRoDHRocmVlZWlnaHRocwtmaXZlZWlnaHRo
    cwxzZXZlbmVpZ2h0aHMKZmlndXJlZGFzaAd1bmkwMEFEB3VuaTIwMDMHdW5pMjAwMgd1bmkyMDA3
    B3VuaTIwMDgHdW5pMDBBMAd1bmkyMDBCBEV1cm8HdW5pMjBCOQd1bmkyMjE5B3VuaTIyMTUIZW1w
    dHlzZXQHdW5pMjEyNgd1bmkyMjA2B3VuaTAwQjUHdW5pRjhGRgd1bmkyMTE3B3VuaTIxMTMJZXN0
    aW1hdGVkB3VuaTIxMTYHdW5pMjEyMAd1bmkwMzA4B3VuaTAzMDcJZ3JhdmVjb21iCWFjdXRlY29t
    Ygd1bmkwMzBCDWNhcm9uY29tYi5hbHQHdW5pMDMwMgd1bmkwMzBDB3VuaTAzMDYHdW5pMDMwQQl0
    aWxkZWNvbWIHdW5pMDMwNAd1bmkwMzEyB3VuaTAzMjYHdW5pMDMyNwd1bmkwMzI4B3VuaTAzMzUH
    dW5pMDMzNgd1bmkwMzM3B3VuaTAzMzgHdW5pMDJCQwd1bmkwMkM5CWNhcm9uLmFsdAd1bmkyMEJG
    B3VuaUUwRkYHdW5pRUZGRAd1bmlGMDAwAAEAAf//AA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAABuAG4AZABkArwAAAK8ArwAAAAAAsb/9gK8Asb/9v/2AG4AbgBkAGQBe/+/
    ArwCvAAAAAABhf+1ArwCxv/2AAAAbgBuAGQAZAK8AV8CvAK8AAAAAAMlAVUCvALG//b/9gAYABgA
    GAAYAACwACwgsABVWEVZICBLuAAOUUuwBlNaWLA0G7AoWWBmIIpVWLACJWG5CAAIAGNjI2IbISGw
    AFmwAEMjRLIAAQBDYEItsAEssCBgZi2wAiwgZCCwwFCwBCZasigBC0NFY0WwBkVYIbADJVlSW1gh
    IyEbilggsFBQWCGwQFkbILA4UFghsDhZWSCxAQtDRWNFYWSwKFBYIbEBC0NFY0UgsDBQWCGwMFkb
    ILDAUFggZiCKimEgsApQWGAbILAgUFghsApgGyCwNlBYIbA2YBtgWVlZG7ACJbAKQ2OwAFJYsABL
    sApQWCGwCkMbS7AeUFghsB5LYbgQAGOwCkNjuAUAYllZZGFZsAErWVkjsABQWGVZWS2wAywgRSCw
    BCVhZCCwBUNQWLAFI0KwBiNCGyEhWbABYC2wBCwjISMhIGSxBWJCILAGI0KwBkVYG7EBC0NFY7EB
    C0OwBGBFY7ADKiEgsAZDIIogirABK7EwBSWwBCZRWGBQG2FSWVgjWSFZILBAU1iwASsbIbBAWSOw
    AFBYZVktsAUssAdDK7IAAgBDYEItsAYssAcjQiMgsAAjQmGwAmJmsAFjsAFgsAUqLbAHLCAgRSCw
    DENjuAQAYiCwAFBYsEBgWWawAWNgRLABYC2wCCyyBwwAQ0VCKiGyAAEAQ2BCLbAJLLAAQyNEsgAB
    AENgQi2wCiwgIEUgsAErI7AAQ7AEJWAgRYojYSBkILAgUFghsAAbsDBQWLAgG7BAWVkjsABQWGVZ
    sAMlI2FERLABYC2wCywgIEUgsAErI7AAQ7AEJWAgRYojYSBksCRQWLAAG7BAWSOwAFBYZVmwAyUj
    YUREsAFgLbAMLCCwACNCsgsKA0VYIRsjIVkqIS2wDSyxAgJFsGRhRC2wDiywAWAgILANQ0qwAFBY
    ILANI0JZsA5DSrAAUlggsA4jQlktsA8sILAQYmawAWMguAQAY4ojYbAPQ2AgimAgsA8jQiMtsBAs
    S1RYsQRkRFkksA1lI3gtsBEsS1FYS1NYsQRkRFkbIVkksBNlI3gtsBIssQAQQ1VYsRAQQ7ABYUKw
    DytZsABDsAIlQrENAiVCsQ4CJUKwARYjILADJVBYsQEAQ2CwBCVCioogiiNhsA4qISOwAWEgiiNh
    sA4qIRuxAQBDYLACJUKwAiVhsA4qIVmwDUNHsA5DR2CwAmIgsABQWLBAYFlmsAFjILAMQ2O4BABi
    ILAAUFiwQGBZZrABY2CxAAATI0SwAUOwAD6yAQEBQ2BCLbATLACxAAJFVFiwECNCIEWwDCNCsAsj
    sARgQiBgsAFhtRISAQAPAEJCimCxEgYrsIkrGyJZLbAULLEAEystsBUssQETKy2wFiyxAhMrLbAX
    LLEDEystsBgssQQTKy2wGSyxBRMrLbAaLLEGEystsBsssQcTKy2wHCyxCBMrLbAdLLEJEystsCks
    IyCwEGJmsAFjsAZgS1RYIyAusAFdGyEhWS2wKiwjILAQYmawAWOwFmBLVFgjIC6wAXEbISFZLbAr
    LCMgsBBiZrABY7AmYEtUWCMgLrABchshIVktsB4sALANK7EAAkVUWLAQI0IgRbAMI0KwCyOwBGBC
    IGCwAWG1EhIBAA8AQkKKYLESBiuwiSsbIlktsB8ssQAeKy2wICyxAR4rLbAhLLECHistsCIssQMe
    Ky2wIyyxBB4rLbAkLLEFHistsCUssQYeKy2wJiyxBx4rLbAnLLEIHistsCgssQkeKy2wLCwgPLAB
    YC2wLSwgYLASYCBDI7ABYEOwAiVhsAFgsCwqIS2wLiywLSuwLSotsC8sICBHICCwDENjuAQAYiCw
    AFBYsEBgWWawAWNgI2E4IyCKVVggRyAgsAxDY7gEAGIgsABQWLBAYFlmsAFjYCNhOBshWS2wMCwA
    sQACRVRYsQwKRUKwARawLyqxBQEVRVgwWRsiWS2wMSwAsA0rsQACRVRYsQwKRUKwARawLyqxBQEV
    RVgwWRsiWS2wMiwgNbABYC2wMywAsQwKRUKwAUVjuAQAYiCwAFBYsEBgWWawAWOwASuwDENjuAQA
    YiCwAFBYsEBgWWawAWOwASuwABa0AAAAAABEPiM4sTIBFSohLbA0LCA8IEcgsAxDY7gEAGIgsABQ
    WLBAYFlmsAFjYLAAQ2E4LbA1LC4XPC2wNiwgPCBHILAMQ2O4BABiILAAUFiwQGBZZrABY2CwAENh
    sAFDYzgtsDcssQIAFiUgLiBHsAAjQrACJUmKikcjRyNhIFhiGyFZsAEjQrI2AQEVFCotsDgssAAW
    sBEjQrAEJbAEJUcjRyNhsQoAQrAJQytlii4jICA8ijgtsDkssAAWsBEjQrAEJbAEJSAuRyNHI2Eg
    sAQjQrEKAEKwCUMrILBgUFggsEBRWLMCIAMgG7MCJgMaWUJCIyCwCEMgiiNHI0cjYSNGYLAEQ7AC
    YiCwAFBYsEBgWWawAWNgILABKyCKimEgsAJDYGQjsANDYWRQWLACQ2EbsANDYFmwAyWwAmIgsABQ
    WLBAYFlmsAFjYSMgILAEJiNGYTgbI7AIQ0awAiWwCENHI0cjYWAgsARDsAJiILAAUFiwQGBZZrAB
    Y2AjILABKyOwBENgsAErsAUlYbAFJbACYiCwAFBYsEBgWWawAWOwBCZhILAEJWBkI7ADJWBkUFgh
    GyMhWSMgILAEJiNGYThZLbA6LLAAFrARI0IgICCwBSYgLkcjRyNhIzw4LbA7LLAAFrARI0IgsAgj
    QiAgIEYjR7ABKyNhOC2wPCywABawESNCsAMlsAIlRyNHI2GwAFRYLiA8IyEbsAIlsAIlRyNHI2Eg
    sAUlsAQlRyNHI2GwBiWwBSVJsAIlYbkIAAgAY2MjIFhiGyFZY7gEAGIgsABQWLBAYFlmsAFjYCMu
    IyAgPIo4IyFZLbA9LLAAFrARI0IgsAhDIC5HI0cjYSBgsCBgZrACYiCwAFBYsEBgWWawAWMjICA8
    ijgtsD4sIyAuRrACJUawEUNYUBtSWVggPFkusS4BFCstsD8sIyAuRrACJUawEUNYUhtQWVggPFku
    sS4BFCstsEAsIyAuRrACJUawEUNYUBtSWVggPFkjIC5GsAIlRrARQ1hSG1BZWCA8WS6xLgEUKy2w
    QSywOCsjIC5GsAIlRrARQ1hQG1JZWCA8WS6xLgEUKy2wQiywOSuKICA8sAQjQoo4IyAuRrACJUaw
    EUNYUBtSWVggPFkusS4BFCuwBEMusC4rLbBDLLAAFrAEJbAEJiAgIEYjR2GwCiNCLkcjRyNhsAlD
    KyMgPCAuIzixLgEUKy2wRCyxCAQlQrAAFrAEJbAEJSAuRyNHI2EgsAQjQrEKAEKwCUMrILBgUFgg
    sEBRWLMCIAMgG7MCJgMaWUJCIyBHsARDsAJiILAAUFiwQGBZZrABY2AgsAErIIqKYSCwAkNgZCOw
    A0NhZFBYsAJDYRuwA0NgWbADJbACYiCwAFBYsEBgWWawAWNhsAIlRmE4IyA8IzgbISAgRiNHsAEr
    I2E4IVmxLgEUKy2wRSyxADgrLrEuARQrLbBGLLEAOSshIyAgPLAEI0IjOLEuARQrsARDLrAuKy2w
    RyywABUgR7AAI0KyAAEBFRQTLrA0Ki2wSCywABUgR7AAI0KyAAEBFRQTLrA0Ki2wSSyxAAEUE7A1
    Ki2wSiywNyotsEsssAAWRSMgLiBGiiNhOLEuARQrLbBMLLAII0KwSystsE0ssgAARCstsE4ssgAB
    RCstsE8ssgEARCstsFAssgEBRCstsFEssgAARSstsFIssgABRSstsFMssgEARSstsFQssgEBRSst
    sFUsswAAAEErLbBWLLMAAQBBKy2wVyyzAQAAQSstsFgsswEBAEErLbBZLLMAAAFBKy2wWiyzAAEB
    QSstsFssswEAAUErLbBcLLMBAQFBKy2wXSyyAABDKy2wXiyyAAFDKy2wXyyyAQBDKy2wYCyyAQFD
    Ky2wYSyyAABGKy2wYiyyAAFGKy2wYyyyAQBGKy2wZCyyAQFGKy2wZSyzAAAAQistsGYsswABAEIr
    LbBnLLMBAABCKy2waCyzAQEAQistsGksswAAAUIrLbBqLLMAAQFCKy2wayyzAQABQistsGwsswEB
    AUIrLbBtLLEAOisusS4BFCstsG4ssQA6K7A+Ky2wbyyxADorsD8rLbBwLLAAFrEAOiuwQCstsHEs
    sQE6K7A+Ky2wciyxATorsD8rLbBzLLAAFrEBOiuwQCstsHQssQA7Ky6xLgEUKy2wdSyxADsrsD4r
    LbB2LLEAOyuwPystsHcssQA7K7BAKy2weCyxATsrsD4rLbB5LLEBOyuwPystsHossQE7K7BAKy2w
    eyyxADwrLrEuARQrLbB8LLEAPCuwPistsH0ssQA8K7A/Ky2wfiyxADwrsEArLbB/LLEBPCuwPist
    sIAssQE8K7A/Ky2wgSyxATwrsEArLbCCLLEAPSsusS4BFCstsIMssQA9K7A+Ky2whCyxAD0rsD8r
    LbCFLLEAPSuwQCstsIYssQE9K7A+Ky2whyyxAT0rsD8rLbCILLEBPSuwQCstsIksswkEAgNFWCEb
    IyFZQiuwCGWwAyRQeLEFARVFWDBZLQAAAABLuADIUlixAQGOWbABuQgACABjcLEAB0K1AEAwIAQA
    KrEAB0JACkUCNQglCBUIBAgqsQAHQkAKRwA9Bi0GHQYECCqxAAtCvRGADYAJgAWAAAQACSqxAA9C
    vQBAAEAAQABAAAQACSqxAwBEsSQBiFFYsECIWLEDZESxJgGIUVi6CIAAAQRAiGNUWLEDAERZWVlZ
    QApHADcGJwYXBgQMKrgB/4WwBI2xAgBEswVkBgBERAAAAAAAAAEAAAAA""".replace("\n", "")
    with open("font.ttf", "wb") as font_file:
        font_file.write(base64.b64decode(b64fontfile))

class Stack(object):
    """docstring for Stack."""
    def __init__(self):
        super(Stack, self).__init__()
        self.stack = []

    def push(self, name, linein, attrs={}, log=False):
        data = {
            "name"      : name,
            "linein"    : linein,
            "lineout"   : -1,
            "attrs"     : attrs
        }
        self.stack.append(data)
        if log: print("[PUSH]", self.stack[-1])

    def pop(self, name, lineout, log=False):
        if len(self.stack) != 0:
            if self.stack[-1]["name"] != name:
                print("[WARN] First element of the stack is \"" + self.stack[-1]["name"] +"\" and not \"" + name + "\"")
                return None
            else:
                data = self.stack[-1]
                data["lineout"] = lineout
                self.stack = self.stack[:-1]
                if log: print("[POP_]", data)
                return data
        else:
            return None

    def currentstack(self):
        stack_el_names = [e["name"] for e in self.stack]
        if len(stack_el_names) != 0:
            maxlen = max([len(e) for e in stack_el_names])
            return '\n'.join(["|" + name.center(maxlen, " ") + "|" for name in stack_el_names[::-1]]) + "\n|" + "_"*maxlen + "|"
        else:
            return "\n|_EMPTY_STACK_|"

class HTMLParser(object):
    """docstring for HTMLParser."""
    def __init__(self, htmltext):
        def rmsep(s):
            while s.startswith(" ") or  s.startswith("\t") : s=s[1:]
            return s
        super(HTMLParser, self).__init__()
        self.htmltext       = [rmsep(line) for line in htmltext.replace("<", "\n<").replace(">", ">\n").split("\n") if rmsep(line) != "\n" and rmsep(line) !=""]
        self.tags_stack     = Stack()
        self.parsedresult   = []

    def to_be_ignored(self,line):
        if line == "<!DOCTYPE html>": return True
        elif line.startswith("<!--"): return True
        else: return False

    def parse(self, log=False) :
        def tagparser(line):
            if line.startswith("<"): line=line[1:]
            if line.endswith("/>"):  line=line[:-2]
            elif line.endswith(">"): line=line[:-1]
            line = line.split(" ", 1)
            tagname = line[0]
            line = line[1]
            tmp = {
                "parsing_args" : False,
                "expected_end" : "",
                "kw_name" : "",
                "kw_args" : [],
                "kw_arg" : ""
            }
            attrs = {}

            lastc = ""
            for c in line:
                #print(c, end=" ")
                if c in ["\"", "\'"] and lastc != "\\":
                    if tmp["parsing_args"] == True:
                        #print("\n[END] args")
                        tmp["kw_args"].append(tmp["kw_arg"])
                        if len(tmp["kw_args"]) == 1 : tmp["kw_args"]=tmp["kw_args"][0]
                        attrs[tmp["kw_name"]] = tmp["kw_args"]
                        tmp["parsing_args"] = False
                        tmp["kw_name"]  = ""
                        tmp["kw_args"]  = []
                        tmp["kw_arg"]   = ""
                    else:
                        #print("\n[BEGIN] args")
                        tmp["parsing_args"] = True
                else:
                    if tmp["parsing_args"]:
                        if c == " ":
                            tmp["kw_args"].append(tmp["kw_arg"])
                            tmp["kw_arg"] = ""
                        else:
                            tmp["kw_arg"] += c
                    else:
                        if c != " " and c != "=": tmp["kw_name"] += c
                lastc = c
            return tagname, attrs
        # ========================================================
        self.parsedresult = []
        for k in range(len(self.htmltext)) :
            line = self.htmltext[k]
            if self.to_be_ignored(line):
                if log: print("[IGNORED]", line)
            elif line.startswith("</") and line.endswith(">"):
                tagname = line[2:-1]
                if log : print(tagname)
                if tagname != "br":
                    self.parsedresult.append(self.tags_stack.pop(tagname, k))
                if log: print(self.tags_stack.currentstack(), "\n")

            elif line.startswith("<") and line.endswith("/>"):
                if " " in line:
                    tagname, attrs = tagparser(line)
                else:
                    tagname = line[1:-2]
                if log : print(tagname)
                if tagname != "br":
                    self.tags_stack.push(tagname, k, attrs, log)
                if tagname != "br":
                    self.parsedresult.append(self.tags_stack.pop(tagname, k, log))
                if log: print(self.tags_stack.currentstack(), "\n")

            elif line.startswith("<") and line.endswith(">"):
                if " " in line:
                    tagname, attrs = tagparser(line)
                else:
                    tagname = line[1:-1]
                if log : print(tagname)
                if tagname != "br":
                    self.tags_stack.push(tagname, k, attrs, log)
                if log: print(self.tags_stack.currentstack(), "\n")
            # Sort self.parsedresult by value of key linein
            self.parsedresult = sorted(self.parsedresult, key=lambda t: t["linein"])
        return self.parsedresult

    def to_text(self, entry):
        if entry in self.parsedresult:
            return '\n'.join(self.htmltext[entry["linein"]:entry["lineout"]+1])

    def find_by_tag(self, tagname):
        if len(self.parsedresult) == 0:
            self.parse()
        out = []
        for entry in self.parsedresult:
            if entry["name"] == tagname :
                out.append(entry)
                #out.append('\n'.join(self.htmltext[entry["linein"]:entry["lineout"]+1]))
        return out

    def find_by_property(self, prop, value=""):
        if len(self.parsedresult) == 0:
            self.parse()
        out = []
        if value != "":
            for entry in self.parsedresult:
                for key in entry["attrs"].keys():
                    if key == prop :
                        if entry["attrs"][key] == value:
                            out.append(entry)
                            #out.append('\n'.join(self.htmltext[entry["linein"]:entry["lineout"]+1]))
        else:
            for entry in self.parsedresult:
                for key in entry["attrs"].keys():
                    if key == prop :
                        out.append(entry)
                        #out.append('\n'.join(self.htmltext[entry["linein"]:entry["lineout"]+1]))
        return out

    def autoindent(self): # working fine
        currentindent=0
        out = ""
        for line in self.htmltext :
            if self.to_be_ignored(line):
                out += "\t"*currentindent + line + "\n"
            elif line.startswith("</") and line.endswith(">"):
                currentindent = max(currentindent-1, 0)
                out += "\t"*currentindent + line + "\n"
            elif line.startswith("<!--"):
                out += "\t"*currentindent + line + "\n"
            elif line.startswith("<") and line.endswith("/>"):
                out += "\t"*currentindent + line + "\n"
            elif line.startswith("<") and line.endswith(">"):
                out += "\t"*currentindent + line + "\n"
                currentindent += 1
            else:
                out += "\t"*currentindent + line + "\n"
        return out

class Badge(object):
    """docstring for Badge."""
    def __init__(self, pseudo, points, rank, maxrank, badge):
        super(Badge, self).__init__()
        self.pseudo  = pseudo
        self.points  = points
        self.rank    = rank
        self.maxrank = maxrank
        self.badge   = badge

    def export(self, outfile):
        img         = Image.new("RGB", (300,110), color=(255,255,255))
        authorlogo  = self.border(Image.open("logo.jpg"), bordersize=1)
        rootmelogo  = Image.open("rootmeskull.png") #self.png_background(, alphalevel=0)
        draw        = ImageDraw.Draw(img)
        fontcolor   = (0,0,0)

        logo_offset = [0,0]
        img = self.merge(img, authorlogo, xcoord=logo_offset[0]+10, ycoord=logo_offset[1]+10)
        # img = self.merge(img, rootmelogo, xcoord=img.size[0]-rootmelogo.size[0]-5, ycoord=7)
        img.paste(rootmelogo, (img.size[0]-rootmelogo.size[0]-5,7), rootmelogo)

        fontcolor   = (0,0,0)
        font = ImageFont.truetype("font.ttf", 30)
        draw.text((logo_offset[0]+10+authorlogo.size[0]+10,logo_offset[1]+10), self.pseudo[:18], fontcolor,font=font)

        fontcolor   = (100,100,100)
        font = ImageFont.truetype("font.ttf", 20)

        draw.text(
            (logo_offset[0]+10+authorlogo.size[0]+10,logo_offset[1]+10+9*authorlogo.size[1]//16),
            str(self.points) + " Points",
            fontcolor,
            font=font
        )

        fontcolor   = (50,50,50)

        draw.text(
            (10, img.size[1]-30),
            str(self.badge),
            fontcolor,
            font=font
        )

        fontcolor   = (100,100,100)

        w,h = font.getsize(str(self.rank+"/"+self.maxrank))
        draw.text(
            (((img.size[0]-10)-w),(img.size[1]-30)),
            str(self.rank+"/"+self.maxrank),
            fontcolor,
            font=font,
            anchor="L"
        )

        img = self.border(img, bordersize=2)
        img.save(outfile)


    def border(self, img, bordersize=1, bordercolor=(0,0,0)):
        pixels = img.load()
        for i in list(range(0, bordersize))+list(range(img.size[0]-bordersize, img.size[0])):         # for every col:
            for j in range(img.size[1]):
                pixels[i,j] = bordercolor
        for i in range(img.size[0]):
            for j in list(range(0, bordersize))+list(range(img.size[1]-bordersize, img.size[1])):     # For every row
                pixels[i,j] = bordercolor
        return img

    def merge(self, img1, img2, xcoord=0,  ycoord=0):
        """Documentation for merge"""
        pixels1 = img1.load()                 # create the pixel map
        pixels2 = img2.load()                 # create the pixel map
        for i in range(img1.size[0]):         # for every col:
            for j in range(img1.size[1]):     # For every row
                (r1, g1, b1) = pixels1[i,j]
                try:
                    pixels1[xcoord+i,ycoord+j] = pixels2[i,j]
                except Exception:
                    pixels1[i,j] = (r1, g1, b1)
        return img1

    def png_background(self, img, backgroundcolor=(255,255,255), alphalevel=0.5):
        """Documentation for merge"""
        pixels = img.load()
        imgout = Image.new("RGB", img.size)
        pixelsout = imgout.load()
        for i in range(img.size[0]):
            for j in range(img.size[1]):
                (r, g, b, a) = pixels[i,j]
                if a <= alphalevel:
                    pixelsout[i,j] = (backgroundcolor[0], backgroundcolor[1], backgroundcolor[2])
                else:
                    pixelsout[i,j] = (int(r*(a/255)), int(g*(a/255)), int(b*(a/255)))
        return imgout

import sys
if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage : python3 "+sys.argv[0]+" pseudo")
    else :
        file = sys.argv[1]
        url = """https://www.root-me.org/"""
        #print("wget -q " + url + sys.argv[1] + "?inc=score&lang=fr -O out.html")
        os.system("wget -q \"" + url + sys.argv[1] + "?inc=score&lang=fr\" -O out.html")

        f = open("out.html", "r")
        html = '\n'.join(f.readlines())
        f.close()

        hp = HTMLParser(html)
        hp.parse(log=False)

        data_pseudo = hp.to_text(hp.find_by_property("itemprop", value="givenName")[0])
        hp2 = HTMLParser(data_pseudo)
        hp2.parse(log=False)
        d = hp2.find_by_tag("img")[0]
        pseudo = d["attrs"]["alt"]
        logo_link = d["attrs"]["src"]
        print("pseudo    :", pseudo)
        print("logo_link :", url+logo_link)

        os.system("wget -q " + url+logo_link + " -O logo.jpg")
        os.system("wget -q \"https://www.root-me.org/local/cache-vignettes/L48xH48/rblackGrand48-0dba3.png\" -O rootmeskull.png")

        data_user = [e for e in hp.find_by_tag("span") if e["attrs"]["class"] == ['color1', 'tl']]#[:2]
        score = hp.to_text(data_user[0]).replace("\n", "").split("&nbsp;")[0].split("<span class=\"color1 tl\">")[1]
        print("score     :", score)

        rank = hp.to_text(data_user[1]).replace("\n", "").replace("<span class=\"gris\">", "").replace("<span class=\"color1 tl\">", "").replace("</span></span>", "").split("/")
        print("rank      :", rank[0], "/", rank[1])

        badge = hp.to_text(data_user[2]).replace("\n", "").split("&nbsp;")[0].split("<span class=\"color1 tl\">")[1]
        print("badge     :", badge)

        install_font()
        Badge(pseudo, score, rank[0], rank[1], badge).export("badge.png")

        os.system("rm logo.jpg out.html rootmeskull.png font.ttf")
